In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#import plotly
pd.set_option('display.max_columns', 50)

In [45]:
death = pd.read_excel('death.xlsx')
death.head()

,County,FIPS,Met Objective of 45.5? (1),Age-Adjusted Death Rate,Lower 95% Confidence Interval for Death Rate,Upper 95% Confidence Interval for Death Rate,Average Deaths per Year,Recent Trend (2),Recent 5-Year Trend (2) in Death Rates,Lower 95% Confidence Interval for Trend,Upper 95% Confidence Interval for Trend
0,United States,0,No,46,45.9,46.1,157376,falling,-2.4,-2.6,-2.2
1,"Perry County, Kentucky",21193,No,125.6,108.9,144.2,43,stable,-0.6,-2.7,1.6
2,"Powell County, Kentucky",21197,No,125.3,100.2,155.1,18,stable,1.7,0,3.4
3,"North Slope Borough, Alaska",2185,No,124.9,73,194.7,5,**,**,**,**
4,"Owsley County, Kentucky",21189,No,118.5,83.1,165.5,8,stable,2.2,-0.4,4.8

In [46]:
incd = pd.read_excel('incd.xlsx')
incd.head()

,County,FIPS,"Age-Adjusted Incidence Rate(Ê) - cases per 100,000",Lower 95% Confidence Interval,Upper 95% Confidence Interval,Average Annual Count,Recent Trend,Recent 5-Year Trend (ˆ) in Incidence Rates,Lower 95% Confidence Interval.1,Upper 95% Confidence Interval.1
0,"US (SEER+NPCR)(1,10)",0,62.4,62.3,62.6,214614,falling,-2.5,-3,-2
1,"Autauga County, Alabama(6,10)",1001,74.9,65.1,85.7,43,stable,0.5,-14.9,18.6
2,"Baldwin County, Alabama(6,10)",1003,66.9,62.4,71.7,170,stable,3,-10.2,18.3
3,"Barbour County, Alabama(6,10)",1005,74.6,61.8,89.4,25,stable,-6.4,-18.3,7.3
4,"Bibb County, Alabama(6,10)",1007,86.4,71,104.2,23,stable,-4.5,-31.4,32.9

In [47]:
merged_data = pd.read_excel('merged_data.xlsx', index_col=0)

In [48]:
merged_data.head()

,State,AreaName,All_Poverty,M_Poverty,F_Poverty,FIPS,Med_Income,Med_Income_White,Med_Income_Black,Med_Income_Nat_Am,Med_Income_Asian,Hispanic,M_With,M_Without,F_With,F_Without,All_With,All_Without,fips_x,Incidence_Rate,Avg_Ann_Incidence,recent_trend,fips_y,Mortality_Rate,Avg_Ann_Deaths
0,AK,"Aleutians East Borough, Alaska",553,334,219,2013,61518.0,72639.0,31250.0,54750.0,62679.0,51250.0,876,1317,566,540,1442,1857,2013,*,3 or fewer,*,2013,*,*
1,AK,"Aleutians West Census Area, Alaska",499,273,226,2016,84306.0,97321.0,93750.0,48750.0,81250.0,77500.0,2470,769,1707,564,4177,1333,2016,*,3 or fewer,*,2016,*,*
2,AK,"Anchorage Municipality, Alaska",23914,10698,13216,2020,78326.0,87235.0,50535.0,53935.0,63757.0,53926.0,120747,23245,122426,21393,243173,44638,2020,61.5,131,stable,2020,47.3,96
3,AK,"Bethel Census Area, Alaska",4364,2199,2165,2050,51012.0,92647.0,73661.0,41594.0,110625.0,160114.0,6396,2708,6627,1774,13023,4482,2050,62.7,6,stable,2050,58.3,5
4,AK,"Bristol Bay Borough, Alaska",69,33,36,2060,79750.0,88000.0,NaN,63333.0,NaN,25625.0,419,124,349,67,768,191,2060,*,3 or fewer,*,2060,*,*

In [49]:
merged_data.columns

Index(['State', 'AreaName', 'All_Poverty', 'M_Poverty', 'F_Poverty', 'FIPS',
       'Med_Income', 'Med_Income_White', 'Med_Income_Black',
       'Med_Income_Nat_Am', 'Med_Income_Asian', 'Hispanic', 'M_With',
       'M_Without', 'F_With', 'F_Without', 'All_With', 'All_Without', 'fips_x',
       'Incidence_Rate', 'Avg_Ann_Incidence', 'recent_trend', 'fips_y',
       'Mortality_Rate', 'Avg_Ann_Deaths'],
      dtype='object')

In [50]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3134 entries, 0 to 3133
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              3134 non-null   object
 1   AreaName           3134 non-null   object
 2   All_Poverty        3134 non-null   int64
 3   M_Poverty          3134 non-null   int64
 4   F_Poverty          3134 non-null   int64
 5   FIPS               3134 non-null   int64
 6   Med_Income         3133 non-null   float64
 7   Med_Income_White   3132 non-null   float64
 8   Med_Income_Black   1924 non-null   float64
 9   Med_Income_Nat_Am  1474 non-null   float64
 10  Med_Income_Asian   1377 non-null   float64
 11  Hispanic           2453 non-null   float64
 12  M_With             3134 non-null   int64
 13  M_Without          3134 non-null   int64
 14  F_With             3134 non-null   int64
 15  F_Without          3134 non-null   int64
 16  All_With           3134 non-null   int64
 17  All_Without        3134 non-null   int64
 18  fips_x             3134 non-null   int64
 19  Incidence_Rate     3134 non-null   object
 20  Avg_Ann_Incidence  3134 non-null   object
 21  recent_trend       3134 non-null   object
 22  fips_y             3134 non-null   int64
 23  Mortality_Rate     3134 non-null   object
 24  Avg_Ann_Deaths     3134 non-null   object
dtypes: float64(6), int64(12), object(7)
memory usage: 636.6+ KB

In [51]:
merged_data.isna().sum()/31.34

State                 0.000000
AreaName              0.000000
All_Poverty           0.000000
M_Poverty             0.000000
F_Poverty             0.000000
FIPS                  0.000000
Med_Income            0.031908
Med_Income_White      0.063816
Med_Income_Black     38.608807
Med_Income_Nat_Am    52.967454
Med_Income_Asian     56.062540
Hispanic             21.729419
M_With                0.000000
M_Without             0.000000
F_With                0.000000
F_Without             0.000000
All_With              0.000000
All_Without           0.000000
fips_x                0.000000
Incidence_Rate        0.000000
Avg_Ann_Incidence     0.000000
recent_trend          0.000000
fips_y                0.000000
Mortality_Rate        0.000000
Avg_Ann_Deaths        0.000000
dtype: float64

In [52]:
cat_cols = ['State', 'AreaName', 'Incidence_Rate', 'Avg_Ann_Incidence', 'recent_trend', 'Mortality_Rate', 'Avg_Ann_Deaths']
def get_unique_vals(col):
    print("Unique Values in Column {} are: ".format(col.name), col.unique())
    print('\n\n\n')
    
merged_data[cat_cols].apply(get_unique_vals)

Unique Values in Column State are:  ['AK' 'AL' 'AR' 'AZ' 'CA' 'CO' 'CT' 'DC' 'DE' 'FL' 'GA' 'HI' 'IA' 'ID'
 'IL' 'IN' 'KS' 'KY' 'LA' 'MA' 'MD' 'ME' 'MI' 'MN' 'MO' 'MS' 'MT' 'NC'
 'ND' 'NE' 'NH' 'NJ' 'NM' 'NV' 'NY' 'OH' 'OK' 'OR' 'PA' 'RI' 'SC' 'SD'
 'TN' 'TX' 'UT' 'VA' 'VT' 'WA' 'WI' 'WV' 'WY']




Unique Values in Column AreaName are:  ['Aleutians East Borough, Alaska' 'Aleutians West Census Area, Alaska'
 'Anchorage Municipality, Alaska' ... 'Uinta County, Wyoming'
 'Washakie County, Wyoming' 'Weston County, Wyoming']




Unique Values in Column Incidence_Rate are:  ['*' 61.5 62.7 58.1 35.1 64.9 88.3 74.7 69.7 103.6 153.4 67.6 44 76.8 66.1
 58.3 74.9 66.9 74.6 86.4 65.8 84.2 75.4 82.4 73.9 49.2 69.5 83.3 71.5
 75.9 73.5 82.6 83 69.6 76.7 76.2 60.8 78.1 75.5 81.9 77.3 72.4 90.3 87.9
 71 66.5 70.8 80.9 65.1 80.4 69.3 88.1 59.4 73.4 57.6 57.9 64.8 61.6 74.2
 79.4 62.3 61 83.1 65.6 61.8 78.7 57.1 55.5 74 70.5 72.3 98.3 74.8 73.2
 90.8 85.9 77 85.6 56.4 67.7 86.3 82.5 59.1 76.4 71.6 108.7 83.6 77.5 72
 75 79.1 75.6 82.2 79.2 77.1 64.7 80.6 96.1 89.2 60.6 94.2 96.2 82.3 55.9
 104.4 97.5 97.2 98.1 102.7 57 63.4 79.5 87 91.9 67.8 82.7 81.2 73.6 89.5
 67.5 69.2 63.9 84 98.8 87.8 114 67.1 89 68 83.9 65.2 91.5 72.1 78.2 70.4
 89.3 91.2 108.5 22.9 46.9 36.7 54.3 45.5 64 54.4 52.2 76.6 39.6 50.9 36.1
 51.9 48 46 58.7 61.4 52.3 56 78.4 50 50.8 61.2 44.3 45.7 55.7 48.8 73.7
 60.9 39.9 51.8 41.6 54.6 56.9 43.7 24.6 42.6 53.3 47.3 44.1 49.6 44.2
 47.2 40.2 49.5 49 56.8 45.3 42.1 41.1 37.6 62.5 60.5 57.4 56.3 66.6 47.9
 58 41.5 42.3 68.1 52.6 47.5 31.7 35.5 48.4 36.9 38.1 34.7 59.5 46.3 48.5
 37.1 28.3 50.3 43.2 24.8 59.2 55.1 34.4 39.7 53.5 36.4 56.1 40 40.5 35.8
 53 24.1 67.3 49.8 29.2 31.5 14.8 54.9 62 65.7 70.2 68.7 65 59 99.5 88.4
 82.1 79.7 43.3 88.2 57.7 100 93.4 66.4 74.3 92.6 69 73.3 71.2 67 42.5
 97.3 76 54.8 103.5 82 59.6 44.4 71.8 93.3 54.7 54.1 68.9 74.4 64.5 54.2
 65.3 87.2 84.4 203.7 95.9 87.5 72.9 89.6 91.3 76.9 84.3 78.6 95.7 67.4
 82.9 60 101.5 64.1 86.9 60.3 90 100.7 74.1 53.2 81.3 58.6 81.1 85.2 68.8
 47.4 81.4 54.5 76.1 71.9 94.7 69.9 64.4 38.8 94.4 104.6 83.4 62.8 68.6
 65.4 79.9 86.5 77.2 83.2 88.9 55 90.4 64.6 66.8 89.1 85.1 72.7 71.7 65.5
 103.1 70.3 78.9 46.8 77.7 77.9 80.1 102 50.6 110.8 56.6 60.7 63.1 100.8
 63 74.5 71.4 62.4 78.5 71.1 91.8 67.9 70.6 84.9 68.2 69.8 77.6 66 44.9
 48.3 45.2 42.4 72.5 61.3 82.8 40.9 45.4 47.6 52.9 57.8 53.6 38.4 86.7
 59.9 63.7 48.7 55.6 58.8 58.5 41.9 50.5 60.1 58.2 73.1 48.2 52.1 98 61.1
 52.4 75.3 84.6 43.4 46.1 43.1 36 41 79 38.7 22.6 35.7 34 55.4 40.4 33.9
 46.5 40.7 41.4 98.7 53.4 41.3 68.3 93.5 66.3 54 89.7 94.1 63.6 72.8 94.3
 88.7 103.4 92.7 58.9 69.1 81.6 90.7 96.6 83.5 92.3 100.9 66.7 79.8 68.4
 105.5 113.1 75.8 63.8 91.6 50.2 61.9 77.8 73.8 94.6 68.5 87.4 79.3 83.8
 70 85.5 46.7 81.7 97.9 81.8 123.2 85.4 85 75.1 101.2 95.1 80.8 84.7 79.6
 64.3 '_' 106.9 109 86 120.6 105.7 110.2 90.9 103.9 94.5 95.2 120.7 103
 108.6 118.6 111.7 96.4 124.6 90.5 149.4 93 112.4 104 97.8 95.8 85.8 129.7
 107.4 127.6 114.5 109.3 80 89.9 118.3 113 116.1 125 113.9 117.7 151.8
 118.5 112.6 98.5 157.5 101.7 109.7 145.1 123.7 118.1 107.7 106.8 94.8
 98.9 102.6 106.5 124.8 148.1 139.7 123 152.9 93.6 111.8 92.4 102.4 87.3
 84.8 100.2 113.2 106.4 80.5 109.1 122.4 80.7 92.2 70.9 87.6 78.3 97.4
 80.3 91.7 92 53.7 52.5 52.8 52.7 35.4 46.6 51.1 84.1 '66.2 #' '48.6 #'
 '53.7 #' '77.1 #' '59.1 #' '104.9 #' '74.9 #' '45.3 #' '60.7 #' '71.4 #'
 '69.7 #' '61.6 #' '71.1 #' '56.1 #' '61.7 #' '73.6 #' '75.6 #' '36.6 #'
 '73 #' '63.2 #' '50.7 #' '51.8 #' '63 #' '80.3 #' '79 #' '63.1 #'
 '66.4 #' '66 #' '62.4 #' '49.6 #' '56.8 #' '58.8 #' '63.5 #' '65.6 #'
 '60.4 #' '69.2 #' '82 #' '61.3 #' '73.4 #' '59.3 #' '77.4 #' '71.9 #'
 '35.7 #' '60 #' '54.6 #' '84 #' '61.9 #' 75.2 '67.3 #' '64.9 #' '54.9 #'
 '69.4 #' '50.1 #' '58 #' '73.3 #' '63.6 #' '75.3 #' '78.6 #' '77.6 #'
 '63.8 #' '51.2 #' '73.2 #' '97 #' '87.3 #' '68.2 #' '39.3 #' '57.9 #'
 '81 #' '69.1 #' '69.5 #' '65.7 #' '50.2 #' '70.8 #' '77.9 #' '73.5 #'
 '54.4 #' '90.7 #' 90.1 77.4 67.2 86.8 70.1 110 93.1 39.5 100.1 100.3
 103.3 76.5 87.7 60.4 114.1 88.8 112.7 88.6 59.8 92.9 92.8 95 64.2 99
 114.9 75.7 76.3 86.2 78 49.9 95.6 62.9 106 55.8 90.6 114.7 95.3 52 58.4
 97.1 42.8 85.3 48.9 62.1 71.3 66.2 81 96.9 73 56.5 57.5 85.7 84.5 95.5
 51.4 59.7 43.5 42.7 56.7 40.6 53.9 49.3 32.5 45.9 43.8 63.3 48.1 59.3
 57.3 42.2 29.3 36.8 72.6 53.8 39.4 41.2 44.7 26.5 13.5 34.8 55.2 37.3
 47.8 35 '__' 50.4 61.7 89.8 72.2 87.1 106.2 86.6 65.9 55.3 70.7 69.4 48.6
 56.2 114.2 80.2 60.2 88.5 62.2 51.3 63.2 53.1 43.9 45.6 62.6 47 51 81.5
 96 49.4 38.6 45 46.4 104.7 105.9 96.8 99.2 102.8 88 100.4 102.9 83.7 98.6
 63.5 98.2 93.8 116 109.2 101.4 45.1 44.5 50.7 32.2 32.9 39.2 32.7 51.7 42
 99.4 38.5 49.7 44.8 30.3 38.2 20.4 15.8 25 29.5 32.6 25.8 32.1 18.2 27.6
 18.5 34.5 29.7 33.6 91.1 37.2 57.2 40.8 51.2 32 28.8 107.3 167 110.1
 100.5 127.9 37 47.7 41.7 51.5 99.8 111.5 115.7 78.8 41.8 46.2 36.3 23.7]




Unique Values in Column Avg_Ann_Incidence are:  ['3 or fewer' 131 6 36 9 39 12 7 51 3 4 5 43 170 25 23 17 120 34 32 10 16
 14 57 44 11 73 66 110 19 28 35 88 58 482 87 37 71 69 8 15 236 33 90 347
 144 116 18 22 24 47 72 108 74 41 135 89 31 21 129 13 26 38 56 78 121 45
 84 29 27 62 30 59 277 20 100 46 119 81 52 2059 280 628 201 203 115 687
 169 554 411 86 371 54 70 3701 76 145 163 92 75 1326 222 1031 793 807 1485
 459 353 161 375 189 705 99 154 246 288 273 174 344 182 253 94 264 282 262
 124 102 101 571 662 160 718 224 98 351 147 387 239 185 647 1129 233 244
 268 77 685 281 241 155 895 180 400 651 130 67 328 493 177 1310 83 153 48
 588 1183 552 1032 631 106 166 479 53 568 55 91 134 50 183 341 311 431 96
 42 148 49 61 79 107 550 80 152 309 191 68 3359 63 529 266 379 113 40 97
 140 265 127 219 151 414 85 252 227 65 64 412 103 133 682 212 '_' 93 206
 104 759 240 60 340 242 126 179 247 476 602 368 511 430 448 616 82 364 661
 117 184 118 361 512 237 187 143 399 157 756 866 105 173 141 172 1634 220
 542 109 195 854 275 178 111 211 202 367 452 158 95 406 338 283 230 580
 342 136 122 250 279 235 475 287 645 276 171 274 '__' 258 641 226 886 1218
 569 992 892 245 432 248 1161 188 1195 164 615 285 139 181 1108 736 673
 149 259 306 232 123 507 128 449 156 513 421 231 1193 192 316 487 301 210
 468 225 208 271 308 249 1260 150 503 142 257 324 286 196 424 357 587 200
 702 175 1078 1768 903 330 260 390 190 125 972 590 433 313 137 658]




Unique Values in Column recent_trend are:  ['*' 'stable' 'falling' 'rising' '_' '__']




Unique Values in Column Mortality_Rate are:  ['*' 47.3 58.3 54 34.4 50.1 70.8 76.2 53.9 96.1 124.9 39.6 60.8 59.3 48
 61.3 67.8 59.9 29.7 52.6 63.1 66 43 43.9 69.1 59.7 55.1 61.2 60.2 68.9
 71.9 61.4 63.6 65.3 56.3 66.1 67 67.7 65.8 71.2 34.5 57.8 56.1 64 51.5
 72.2 56.8 70 57.1 55.9 44 41.1 50.4 51.9 51.7 66.6 63.3 52.9 49.9 60.5
 60.3 57.5 47.2 58.5 65 51 61 54.5 54.4 79.8 61.7 69.9 58.6 64.3 47 62.6
 68.3 70.2 47.7 53.3 80.1 70.5 49.2 61.8 75.7 74 62.8 66.9 70.1 51.3 62.5
 69.6 55.6 75.3 83.1 48.4 83.5 67.3 67.9 76.8 82.3 61.9 59 56.6 70.4 72.3
 72.5 73.1 70.9 76.1 64.9 55.8 78.5 90.8 63.5 103.5 71.7 54.7 52 65.9 62.1
 60.4 58.2 71.6 52.7 76 17.7 37 25.6 43.8 33.8 41.8 37.7 37.2 59.1 31 37.3
 33.6 23.1 38.1 30.9 33.4 46 40.2 48.9 36.1 34.3 36.2 42.7 27 36.5 41.4 56
 31.1 43.3 42.1 34.8 31.7 40.6 31.4 32.6 37.1 42.6 29.9 39 36 44.8 34.7
 30.4 29.3 27.6 28.4 48.6 44.3 38.4 52.4 40.7 37.6 30.3 55.3 30.5 33.7
 22.7 24.3 37.8 30.6 35 24 14.9 35.7 41.3 26.1 38.5 43.5 24.6 29.8 46.9
 42.4 40.3 41.2 25.5 36.8 21 21.6 26.4 35.2 40.4 38.7 44.2 44.9 47.5 57
 50.3 53.1 75.2 66.5 55.4 68.4 45.3 64.2 45 73.8 53.8 58.8 49.7 77.7 41.5
 65.2 53.2 49.1 47.8 51.4 48.3 68.6 51.2 52.8 78.3 39.9 42 77.3 84.1 55
 41.7 40.5 45.5 57.3 69.3 50.6 71.1 42.3 61.6 41.9 43.1 66.8 113.5 54.1
 76.3 67.5 75.8 63.4 63.2 65.1 60.1 74.1 51.1 68.1 51.6 81.3 50.2 49.3
 49.4 44.4 74.5 46.7 41.6 62 47.4 59.2 79.3 53.6 60.9 54.8 46.6 34.1 55.5
 64.5 38.3 39.1 50.9 45.6 45.8 64.6 56.4 68.5 45.2 74.9 68.8 60 56.7 70.7
 54.6 62.2 60.6 50 57.6 39.5 64.8 56.2 41 69.7 59.5 44.5 62.9 77.5 87.2
 46.3 40.9 38.8 52.2 79.1 53.7 56.5 54.9 57.2 76.4 53.5 45.7 57.7 56.9
 33.3 32.9 34.6 28.6 35.3 35.4 36.3 58.4 50.5 36.7 36.9 25.7 63 33.5 36.6
 47.6 24.4 43.6 24.8 71.3 50.8 39.3 35.5 61.5 31.8 33.9 22.2 30.7 32.5
 31.9 43.7 25.4 40.8 26.9 31.2 35.8 74.8 27.8 72.4 69.2 44.7 46.2 78.1
 60.7 73.7 54.2 55.7 80.2 57.4 62.3 68.7 52.5 40.1 66.4 67.6 63.9 48.2
 46.1 69.4 74.3 69.5 52.1 46.5 74.4 43.4 51.8 39.8 64.1 71.4 45.1 68 65.7
 80.6 57.9 81.2 80 79.9 42.9 64.4 53 58.1 42.8 52.3 55.2 26.5 26.8 37.5
 45.4 29.6 46.4 33.2 39.2 49 62.7 75.6 67.4 78 73 77.4 73.9 92.7 73.2 59.8
 76.6 88 73.5 98.5 62.4 96.5 80.5 78.8 61.1 98.7 75.9 88.9 83.8 79.6 72.8
 87.9 81.4 95.3 90.2 89.3 104.6 92.5 85.9 85.1 110.3 81.6 77.8 111.1 109.1
 86.6 87 106 67.2 84 84.3 81.5 89.6 94.6 118.5 125.6 85.4 125.3 74.7 89.2
 81.7 91.9 78.2 65.5 79.5 95.6 77.6 66.7 59.6 72.6 70.6 47.9 66.3 45.9
 53.4 44.1 39.4 67.1 73.6 72.1 49.6 42.2 49.5 42.5 47.1 28.8 25 40 68.2
 54.3 63.8 58.9 38.9 72.7 31.5 48.8 32.1 48.7 30 37.9 38 82.7 26.6 38.6
 32.3 34 43.2 48.1 92.3 75 83.6 65.6 74.2 97.2 50.7 84.5 90.5 82 76.7 81.1
 66.2 63.7 76.9 49.8 87.4 71.8 78.4 28.3 21.3 37.4 31.3 22.8 33 48.5 58
 35.1 32.4 39.7 58.7 28.2 36.4 33.1 28.9 32.2 38.2 24.7 25.3 15.8 11.6
 30.1 23 35.9 27.5 65.4 75.1 26.3 64.7 75.4 32 59.4 46.8 35.6 34.9 89 86.8
 84.2 83 81.9 80.8 78.7 73.4 71.5 84.8 103.3 94.9 74.6 22.5 29.5 80.3 23.6
 89.1 32.7 20.7 17.6 9.2 17.2 19.7 22.1 18.8 14.4 12.4 69 34.2 25.1 28.7
 44.6 23.9 29.4 79 95.1 81 29.1]




Unique Values in Column Avg_Ann_Deaths are:  ['*' 96 5 31 8 28 9 6 37 3 4 34 121 20 17 43 15 86 29 21 13 12 33 46 11 39
 63 55 32 90 14 25 27 69 381 71 66 51 10 179 23 75 289 16 117 88 18 38 61
 100 24 54 106 7 19 48 36 95 58 22 49 223 85 91 65 26 42 1463 216 35 464
 146 151 74 495 126 404 79 291 270 53 2876 70 50 979 154 808 595 625 1097
 324 277 120 254 134 472 119 186 200 40 145 250 60 133 177 196 92 77 76
 365 439 99 467 142 62 240 105 171 114 139 487 827 175 194 465 211 183 110
 616 143 279 441 98 236 347 124 885 57 424 102 852 422 777 423 78 107 213
 104 366 187 41 84 30 59 298 81 72 113 47 64 377 56 233 68 136 73 2369 362
 193 257 129 101 165 45 281 198 163 80 111 545 52 157 122 210 251 109 44
 512 67 159 199 262 185 135 326 390 271 713 354 292 471 131 263 299 94 388
 169 116 127 247 527 118 567 123 1136 148 411 227 162 398 176 574 204 132
 150 206 314 115 103 274 245 112 156 402 232 275 172 152 319 317 201 442
 202 207 901 182 181 438 620 824 405 605 573 164 167 740 751 397 221 838
 553 500 376 93 258 352 168 409 328 189 83 327 862 340 219 144 350 89 249
 178 408 903 356 97 87 241 331 268 457 138 130 528 802 1243 137 654 230
 242 108 191 681 396 300 174 484 170]

State                None
AreaName             None
Incidence_Rate       None
Avg_Ann_Incidence    None
recent_trend         None
Mortality_Rate       None
Avg_Ann_Deaths       None
dtype: object

In [53]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3134 entries, 0 to 3133
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              3134 non-null   object
 1   AreaName           3134 non-null   object
 2   All_Poverty        3134 non-null   int64
 3   M_Poverty          3134 non-null   int64
 4   F_Poverty          3134 non-null   int64
 5   FIPS               3134 non-null   int64
 6   Med_Income         3133 non-null   float64
 7   Med_Income_White   3132 non-null   float64
 8   Med_Income_Black   1924 non-null   float64
 9   Med_Income_Nat_Am  1474 non-null   float64
 10  Med_Income_Asian   1377 non-null   float64
 11  Hispanic           2453 non-null   float64
 12  M_With             3134 non-null   int64
 13  M_Without          3134 non-null   int64
 14  F_With             3134 non-null   int64
 15  F_Without          3134 non-null   int64
 16  All_With           3134 non-null   int64
 17  All_Without        3134 non-null   int64
 18  fips_x             3134 non-null   int64
 19  Incidence_Rate     3134 non-null   object
 20  Avg_Ann_Incidence  3134 non-null   object
 21  recent_trend       3134 non-null   object
 22  fips_y             3134 non-null   int64
 23  Mortality_Rate     3134 non-null   object
 24  Avg_Ann_Deaths     3134 non-null   object
dtypes: float64(6), int64(12), object(7)
memory usage: 636.6+ KB

Columns with * :  'Incidence_Rate', 'recent_trend', 'Mortality_Rate', 'Avg_Ann_Deaths'

In [54]:
merged_data['State'].value_counts()

TX    254
GA    159
VA    132
KY    120
MO    115
KS    105
IL    102
NC    100
IA     99
TN     95
NE     93
IN     92
OH     88
MN     87
MI     83
MS     82
OK     77
AR     75
WI     72
FL     67
PA     67
AL     67
SD     65
LA     64
CO     64
NY     62
CA     58
MT     56
WV     55
ND     53
SC     46
ID     44
WA     39
OR     36
NM     33
UT     29
MD     24
AK     23
WY     23
NJ     21
NV     17
ME     16
AZ     15
MA     14
VT     14
NH     10
CT      8
RI      5
HI      5
DE      3
DC      1
Name: State, dtype: int64

In [55]:
merged_data[merged_data['Mortality_Rate'] == '*'].head()

,State,AreaName,All_Poverty,M_Poverty,F_Poverty,FIPS,Med_Income,Med_Income_White,Med_Income_Black,Med_Income_Nat_Am,Med_Income_Asian,Hispanic,M_With,M_Without,F_With,F_Without,All_With,All_Without,fips_x,Incidence_Rate,Avg_Ann_Incidence,recent_trend,fips_y,Mortality_Rate,Avg_Ann_Deaths
0,AK,"Aleutians East Borough, Alaska",553,334,219,2013,61518.0,72639.0,31250.0,54750.0,62679.0,51250.0,876,1317,566,540,1442,1857,2013,*,3 or fewer,*,2013,*,*
1,AK,"Aleutians West Census Area, Alaska",499,273,226,2016,84306.0,97321.0,93750.0,48750.0,81250.0,77500.0,2470,769,1707,564,4177,1333,2016,*,3 or fewer,*,2016,*,*
4,AK,"Bristol Bay Borough, Alaska",69,33,36,2060,79750.0,88000.0,NaN,63333.0,NaN,25625.0,419,124,349,67,768,191,2060,*,3 or fewer,*,2060,*,*
5,AK,"Denali Borough, Alaska",254,139,115,2068,81544.0,81029.0,NaN,47500.0,NaN,NaN,822,253,674,250,1496,503,2068,*,3 or fewer,*,2068,*,*
6,AK,"Dillingham Census Area, Alaska",894,446,448,2070,54173.0,81161.0,NaN,42212.0,NaN,86458.0,1678,900,1837,546,3515,1446,2070,*,3 or fewer,*,2070,*,*

In [56]:
merged_data[merged_data['State'] == 'AK']['recent_trend'].value_counts()

stable    13
*         10
Name: recent_trend, dtype: int64

In [57]:
merged_data[merged_data['recent_trend'] == '_'].head()

,State,AreaName,All_Poverty,M_Poverty,F_Poverty,FIPS,Med_Income,Med_Income_White,Med_Income_Black,Med_Income_Nat_Am,Med_Income_Asian,Hispanic,M_With,M_Without,F_With,F_Without,All_With,All_Without,fips_x,Incidence_Rate,Avg_Ann_Incidence,recent_trend,fips_y,Mortality_Rate,Avg_Ann_Deaths
882,KS,"Allen County, Kansas",2257,957,1300,20001,38698.0,39505.0,38482.0,20833.0,NaN,39500.0,5602,779,5754,741,11356,1520,20001,_,_,_,20001,52.2,10
883,KS,"Anderson County, Kansas",1362,668,694,20003,40696.0,40370.0,NaN,81200.0,NaN,NaN,3391,487,3407,509,6798,996,20003,_,_,_,20003,50.6,6
884,KS,"Atchison County, Kansas",2970,1310,1660,20005,43581.0,44353.0,22375.0,NaN,NaN,NaN,6755,1145,7594,963,14349,2108,20005,_,_,_,20005,51.1,10
885,KS,"Barber County, Kansas",511,245,266,20007,51811.0,51658.0,NaN,NaN,NaN,65938.0,2170,220,2078,261,4248,481,20007,_,_,_,20007,56,4
886,KS,"Barton County, Kansas",4261,1840,2421,20009,44013.0,45325.0,22326.0,18958.0,NaN,22247.0,11051,2075,12159,1703,23210,3778,20009,_,_,_,20009,45.5,17

In [58]:
merged_data[merged_data['recent_trend'] == '_']['State'].unique()

array(['KS', 'MN'], dtype=object)

In [59]:
merged_data[merged_data['recent_trend'] == '__'].head()

,State,AreaName,All_Poverty,M_Poverty,F_Poverty,FIPS,Med_Income,Med_Income_White,Med_Income_Black,Med_Income_Nat_Am,Med_Income_Asian,Hispanic,M_With,M_Without,F_With,F_Without,All_With,All_Without,fips_x,Incidence_Rate,Avg_Ann_Incidence,recent_trend,fips_y,Mortality_Rate,Avg_Ann_Deaths
1958,NV,"Churchill County, Nevada",3802,1765,2037,32001,47415.0,48172.0,50057.0,55250.0,45417.0,35568.0,9756,1871,9845,1873,19601,3744,32001,__,__,__,32001,59.9,18
1959,NV,"Clark County, Nevada",315358,147575,167783,32003,51575.0,54767.0,37604.0,44759.0,60857.0,43244.0,799278,201993,830625,180211,1629903,382204,32003,__,__,__,32003,48.1,901
1960,NV,"Douglas County, Nevada",4984,2264,2720,32005,58535.0,59891.0,61083.0,26950.0,48553.0,40714.0,19911,3602,20431,2952,40342,6554,32005,__,__,__,32005,40.9,32
1961,NV,"Elko County, Nevada",5574,2675,2899,32007,71799.0,73428.0,NaN,43472.0,55714.0,50925.0,22496,3962,20493,3991,42989,7953,32007,__,__,__,32007,39.9,15
1962,NV,"Esmeralda County, Nevada",194,53,141,32009,39271.0,42125.0,NaN,NaN,NaN,NaN,387,128,475,146,862,274,32009,__,__,__,32009,*,*

In [60]:
merged_data[merged_data['recent_trend'] == '__']['State'].unique()

array(['NV'], dtype=object)

In [61]:
merged_data[merged_data['State'] == 'NV']['recent_trend'].unique()

array(['__'], dtype=object)

In [62]:
merged_data[merged_data['State'] == 'KS']['recent_trend'].unique()

array(['_'], dtype=object)

In [63]:
merged_data[merged_data['State'] == 'MN']['recent_trend'].unique()

array(['_'], dtype=object)

KS, MN and NV don't have any data for recent trend, incidence rate or mortality rate across all counties
All other states which have atleast one data point for these columns

In [64]:
print(len(merged_data['State'].unique()))

merged_data = merged_data[merged_data['State']!='NV']
merged_data = merged_data[merged_data['State']!='KS']
merged_data = merged_data[merged_data['State']!='MN']

len(merged_data['State'].unique())

51

48

In [65]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2925 entries, 0 to 3133
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              2925 non-null   object
 1   AreaName           2925 non-null   object
 2   All_Poverty        2925 non-null   int64
 3   M_Poverty          2925 non-null   int64
 4   F_Poverty          2925 non-null   int64
 5   FIPS               2925 non-null   int64
 6   Med_Income         2924 non-null   float64
 7   Med_Income_White   2923 non-null   float64
 8   Med_Income_Black   1852 non-null   float64
 9   Med_Income_Nat_Am  1362 non-null   float64
 10  Med_Income_Asian   1298 non-null   float64
 11  Hispanic           2283 non-null   float64
 12  M_With             2925 non-null   int64
 13  M_Without          2925 non-null   int64
 14  F_With             2925 non-null   int64
 15  F_Without          2925 non-null   int64
 16  All_With           2925 non-null   int64
 17  All_Without        2925 non-null   int64
 18  fips_x             2925 non-null   int64
 19  Incidence_Rate     2925 non-null   object
 20  Avg_Ann_Incidence  2925 non-null   object
 21  recent_trend       2925 non-null   object
 22  fips_y             2925 non-null   int64
 23  Mortality_Rate     2925 non-null   object
 24  Avg_Ann_Deaths     2925 non-null   object
dtypes: float64(6), int64(12), object(7)
memory usage: 594.1+ KB

In [66]:
merged_data.isna().sum()/29.25

State                 0.000000
AreaName              0.000000
All_Poverty           0.000000
M_Poverty             0.000000
F_Poverty             0.000000
FIPS                  0.000000
Med_Income            0.034188
Med_Income_White      0.068376
Med_Income_Black     36.683761
Med_Income_Nat_Am    53.435897
Med_Income_Asian     55.623932
Hispanic             21.948718
M_With                0.000000
M_Without             0.000000
F_With                0.000000
F_Without             0.000000
All_With              0.000000
All_Without           0.000000
fips_x                0.000000
Incidence_Rate        0.000000
Avg_Ann_Incidence     0.000000
recent_trend          0.000000
fips_y                0.000000
Mortality_Rate        0.000000
Avg_Ann_Deaths        0.000000
dtype: float64

In [67]:
merged_data.columns

Index(['State', 'AreaName', 'All_Poverty', 'M_Poverty', 'F_Poverty', 'FIPS',
       'Med_Income', 'Med_Income_White', 'Med_Income_Black',
       'Med_Income_Nat_Am', 'Med_Income_Asian', 'Hispanic', 'M_With',
       'M_Without', 'F_With', 'F_Without', 'All_With', 'All_Without', 'fips_x',
       'Incidence_Rate', 'Avg_Ann_Incidence', 'recent_trend', 'fips_y',
       'Mortality_Rate', 'Avg_Ann_Deaths'],
      dtype='object')

In [68]:
cols_to_fill = ['Med_Income', 'Med_Income_White', 'Med_Income_Black',
       'Med_Income_Nat_Am', 'Med_Income_Asian', 'Hispanic']

def fill_na_with_mean_median_income(df):
    for col in cols_to_fill:
        col_mean = np.mean(df[col])
        df[col].fillna(col_mean, inplace = True)
    return df

filled_merged_data = pd.DataFrame()

for grp in merged_data['State'].unique():
    df = merged_data[merged_data['State'] == grp]
    
    df = fill_na_with_mean_median_income(df)
    
    filled_merged_data = filled_merged_data.append(df)

filled_merged_data.isna().sum()/29.25

/home/aryan/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py:6392: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

State                0.0
AreaName             0.0
All_Poverty          0.0
M_Poverty            0.0
F_Poverty            0.0
FIPS                 0.0
Med_Income           0.0
Med_Income_White     0.0
Med_Income_Black     0.0
Med_Income_Nat_Am    0.0
Med_Income_Asian     0.0
Hispanic             0.0
M_With               0.0
M_Without            0.0
F_With               0.0
F_Without            0.0
All_With             0.0
All_Without          0.0
fips_x               0.0
Incidence_Rate       0.0
Avg_Ann_Incidence    0.0
recent_trend         0.0
fips_y               0.0
Mortality_Rate       0.0
Avg_Ann_Deaths       0.0
dtype: float64

In [69]:
filled_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2925 entries, 0 to 3133
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              2925 non-null   object
 1   AreaName           2925 non-null   object
 2   All_Poverty        2925 non-null   int64
 3   M_Poverty          2925 non-null   int64
 4   F_Poverty          2925 non-null   int64
 5   FIPS               2925 non-null   int64
 6   Med_Income         2925 non-null   float64
 7   Med_Income_White   2925 non-null   float64
 8   Med_Income_Black   2925 non-null   float64
 9   Med_Income_Nat_Am  2925 non-null   float64
 10  Med_Income_Asian   2925 non-null   float64
 11  Hispanic           2925 non-null   float64
 12  M_With             2925 non-null   int64
 13  M_Without          2925 non-null   int64
 14  F_With             2925 non-null   int64
 15  F_Without          2925 non-null   int64
 16  All_With           2925 non-null   int64
 17  All_Without        2925 non-null   int64
 18  fips_x             2925 non-null   int64
 19  Incidence_Rate     2925 non-null   object
 20  Avg_Ann_Incidence  2925 non-null   object
 21  recent_trend       2925 non-null   object
 22  fips_y             2925 non-null   int64
 23  Mortality_Rate     2925 non-null   object
 24  Avg_Ann_Deaths     2925 non-null   object
dtypes: float64(6), int64(12), object(7)
memory usage: 594.1+ KB

In [70]:
cols_with_star = ['Incidence_Rate', 'recent_trend', 'Mortality_Rate', 'Avg_Ann_Deaths']

len(filled_merged_data[filled_merged_data['Incidence_Rate'] == '*'])*100/len(filled_merged_data)

7.213675213675214

In [71]:
for col in cols_with_star:
    filled_merged_data = filled_merged_data[filled_merged_data[col] != '*']
    
len(filled_merged_data)

2618

In [72]:
def fix_hashed_strings(row):
    try:
        row['Incidence_Rate'] = float(row['Incidence_Rate'].replace(' #', ''))
    except:
        pass
    
    return row

filled_merged_data = filled_merged_data.apply(fix_hashed_strings, axis = 1)
filled_merged_data['Incidence_Rate'].unique()

array([ 61.5,  62.7,  58.1,  35.1,  64.9,  88.3,  74.7,  69.7, 103.6,
       153.4,  44. ,  66.1,  74.9,  66.9,  74.6,  86.4,  65.8,  58.3,
        84.2,  75.4,  82.4,  73.9,  49.2,  69.5,  83.3,  71.5,  75.9,
        73.5,  82.6,  83. ,  69.6,  76.7,  76.2,  60.8,  78.1,  75.5,
        81.9,  77.3,  72.4,  90.3,  87.9,  71. ,  66.5,  70.8,  80.9,
        65.1,  80.4,  69.3,  88.1,  59.4,  73.4,  57.6,  57.9,  64.8,
        61.6,  74.2,  79.4,  62.3,  61. ,  83.1,  65.6,  61.8,  78.7,
        57.1,  55.5,  74. ,  70.5,  72.3,  98.3,  74.8,  73.2,  90.8,
        85.9,  77. ,  85.6,  56.4,  67.7,  86.3,  82.5,  59.1,  76.4,
        71.6, 108.7,  83.6,  77.5,  72. ,  75. ,  79.1,  75.6,  82.2,
        79.2,  77.1,  64.7,  80.6,  96.1,  89.2,  60.6,  94.2,  96.2,
        82.3,  55.9, 104.4,  97.5,  97.2,  98.1, 102.7,  57. ,  63.4,
        79.5,  87. ,  91.9,  67.8,  82.7,  81.2,  73.6,  89.5,  67.5,
        69.2,  63.9,  84. ,  98.8,  87.8, 114. ,  67.1,  89. ,  68. ,
        83.9,  65.2,  91.5,  72.1,  78.2,  70.4,  89.3,  91.2, 108.5,
        22.9,  46.9,  36.7,  54.3,  45.5,  64. ,  54.4,  52.2,  76.6,
        39.6,  50.9,  36.1,  51.9,  48. ,  46. ,  58.7,  61.4,  52.3,
        56. ,  78.4,  50. ,  50.8,  61.2,  44.3,  45.7,  55.7,  48.8,
        73.7,  60.9,  39.9,  51.8,  41.6,  54.6,  56.9,  43.7,  42.6,
        53.3,  47.3,  44.1,  49.6,  44.2,  47.2,  40.2,  49.5,  49. ,
        56.8,  45.3,  42.1,  41.1,  37.6,  62.5,  60.5,  57.4,  56.3,
        66.6,  47.9,  58. ,  41.5,  42.3,  68.1,  52.6,  47.5,  31.7,
        35.5,  48.4,  36.9,  34.7,  46.3,  48.5,  37.1,  28.3,  50.3,
        43.2,  59.2,  55.1,  34.4,  39.7,  53.5,  36.4,  56.1,  40. ,
        40.5,  35.8,  67.3,  49.8,  29.2,  31.5,  54.9,  62. ,  65.7,
        70.2,  68.7,  65. ,  59. ,  99.5,  88.4,  82.1,  79.7,  43.3,
        88.2,  57.7, 100. ,  93.4,  66.4,  74.3,  92.6,  69. ,  73.3,
        71.2,  67. ,  42.5,  97.3,  76. ,  54.8, 103.5,  82. ,  59.6,
        44.4,  71.8,  93.3,  54.7,  54.1,  68.9,  74.4,  64.5,  54.2,
        65.3,  87.2,  84.4, 203.7,  95.9,  87.5,  89.6,  91.3,  76.9,
        84.3,  78.6,  95.7,  67.4,  82.9,  60. , 101.5,  86.9,  60.3,
        90. , 100.7,  74.1,  53.2,  81.3,  58.6,  81.1,  85.2,  67.6,
        68.8,  47.4,  81.4,  54.5,  76.1,  71.9,  94.7,  64.4,  94.4,
       104.6,  83.4,  68.6,  65.4,  79.9,  86.5,  77.2,  83.2,  76.8,
        88.9,  55. ,  90.4,  64.6,  66.8,  89.1,  85.1,  72.7,  71.7,
       103.1,  70.3,  78.9,  46.8,  77.7,  77.9,  80.1, 102. ,  50.6,
       110.8,  56.6,  60.7,  65.5,  63.1, 100.8,  63. ,  74.5,  71.4,
        62.4,  78.5,  71.1,  91.8,  67.9,  70.6,  62.8,  69.8,  77.6,
        66. ,  44.9,  48.3,  45.2,  72.5,  61.3,  82.8,  40.9,  45.4,
        47.6,  52.9,  57.8,  64.1,  53.6,  38.4,  86.7,  59.9,  63.7,
        48.7,  55.6,  58.8,  58.5,  41.9,  50.5,  60.1,  58.2,  73.1,
        48.2,  52.1,  98. ,  61.1,  52.4,  75.3,  84.6,  43.4,  43.1,
        36. ,  41. ,  79. ,  38.7,  35.7,  34. ,  55.4,  40.4,  33.9,
        46.5,  40.7,  98.7,  53.4,  41.3,  68.3,  93.5,  66.3,  54. ,
        89.7,  94.1,  63.6,  72.8,  94.3,  88.7, 103.4,  92.7,  58.9,
        69.1,  81.6,  90.7,  96.6,  83.5,  92.3, 100.9,  66.7,  79.8,
        68.4, 105.5, 113.1,  75.8,  63.8,  91.6,  50.2,  61.9,  77.8,
        73.8,  94.6,  68.5,  87.4,  79.3,  83.8,  70. ,  85.5,  46.7,
        69.9,  81.7,  97.9,  81.8, 123.2,  85.4,  85. ,  75.1, 101.2,
        95.1,  80.8,  84.7,  79.6,  64.3, 106.9, 109. ,  86. , 120.6,
       105.7, 110.2,  90.9, 103.9,  94.5,  95.2, 120.7, 103. , 108.6,
        84.9, 118.6, 111.7,  96.4, 124.6,  90.5, 149.4,  93. , 112.4,
       104. ,  97.8,  95.8,  85.8, 129.7, 107.4, 127.6, 114.5, 109.3,
        80. ,  89.9, 118.3, 113. , 116.1, 125. , 113.9, 117.7, 151.8,
       118.5, 112.6,  98.5, 157.5, 101.7, 109.7, 145.1, 123.7, 118.1,
       107.7, 106.8,  94.8,  98.9, 102.6, 106.5, 124.8, 148.1, 139.7,
       123. , 152.9,  93.6,  92.4, 102.4,  87.3,  84.8, 100.2, 113.2,
       106.4,  80.5, 109.1, 122.4,  68.2,  80.7,  92.2,  70.9,  87.6,
        78.3,  97.4,  80.3,  91.7,  92. ,  72.9,  53.7,  52.5,  52.8,
        52.7,  35.4,  46.6,  51.1,  84.1,  66.2,  48.6, 104.9,  61.7,
        36.6,  73. ,  63.2,  50.7,  63.5,  60.4,  59.3,  77.4,  75.2,
        69.4,  50.1,  51.2,  97. ,  39.3,  81. ,  90.1,  67.2,  86.8,
        70.1, 110. ,  93.1,  39.5, 100.1, 100.3, 103.3,  76.5,  87.7,
       114.1,  88.8, 112.7,  88.6,  59.8,  92.9,  92.8,  95. ,  64.2,
        99. , 114.9,  75.7,  76.3,  86.2,  78. ,  49.9,  46.1,  95.6,
        62.9, 106. ,  90.6, 114.7,  95.3,  52. ,  59.5,  58.4,  42.8,
        85.3,  48.9,  62.1,  71.3,  53. ,  96.9,  56.5,  57.5,  85.7,
        84.5,  95.5,  51.4,  59.7,  42.7,  56.7,  40.6,  53.9,  49.3,
        32.5,  45.9,  43.8,  63.3,  48.1,  57.3,  36.8,  72.6,  53.8,
        39.4,  38.1,  44.7,  26.5,  13.5,  34.8,  55.2,  37.3,  47.8,
        35. ,  50.4,  89.8,  72.2,  87.1, 106.2,  86.6,  65.9,  55.3,
        70.7,  56.2, 114.2,  80.2,  60.2,  88.5,  62.2,  51.3,  53.1,
        43.9,  45.6,  62.6,  47. ,  51. ,  81.5,  49.4,  38.6,  45. ,
        46.4, 104.7, 105.9,  96.8,  99.2, 102.8,  88. , 100.4, 102.9,
        83.7,  98.6,  98.2,  93.8, 116. , 109.2, 101.4,  55.8,  42.4,
        45.1,  44.5,  32.9,  39.2,  32.7,  51.7,  99.4,  38.5,  49.7,
        44.8,  30.3,  20.4,  15.8,  25. ,  29.5,  32.1,  29.3,  18.2,
        27.6,  18.5,  29.7,  33.6,  91.1,  37.2,  57.2,  40.8,  32. ,
        28.8, 107.3, 167. , 127.9,  37. ,  42. ,  47.7,  41.7,  51.5,
       111.8,  99.8, 111.5, 115.7,  78.8,  41.8,  46.2,  38.2,  36.3,
        23.7])

In [73]:
filled_merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2618 entries, 2 to 3133
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   State              2618 non-null   object
 1   AreaName           2618 non-null   object
 2   All_Poverty        2618 non-null   int64
 3   M_Poverty          2618 non-null   int64
 4   F_Poverty          2618 non-null   int64
 5   FIPS               2618 non-null   int64
 6   Med_Income         2618 non-null   float64
 7   Med_Income_White   2618 non-null   float64
 8   Med_Income_Black   2618 non-null   float64
 9   Med_Income_Nat_Am  2618 non-null   float64
 10  Med_Income_Asian   2618 non-null   float64
 11  Hispanic           2618 non-null   float64
 12  M_With             2618 non-null   int64
 13  M_Without          2618 non-null   int64
 14  F_With             2618 non-null   int64
 15  F_Without          2618 non-null   int64
 16  All_With           2618 non-null   int64
 17  All_Without        2618 non-null   int64
 18  fips_x             2618 non-null   int64
 19  Incidence_Rate     2618 non-null   float64
 20  Avg_Ann_Incidence  2618 non-null   int64
 21  recent_trend       2618 non-null   object
 22  fips_y             2618 non-null   int64
 23  Mortality_Rate     2618 non-null   float64
 24  Avg_Ann_Deaths     2618 non-null   int64
dtypes: float64(8), int64(14), object(3)
memory usage: 531.8+ KB

In [74]:
filled_merged_data.to_csv('clean_merged.csv', index = False)

### Merged Data Cleaned !!

In [75]:
incd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3141 entries, 0 to 3140
Data columns (total 10 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   County                                              3141 non-null   object
 1    FIPS                                               3141 non-null   int64
 2   Age-Adjusted Incidence Rate(Ê) - cases per 100,000  3141 non-null   object
 3   Lower 95% Confidence Interval                       3141 non-null   object
 4   Upper 95% Confidence Interval                       3141 non-null   object
 5   Average Annual Count                                3141 non-null   object
 6   Recent Trend                                        3141 non-null   object
 7   Recent 5-Year Trend (ˆ) in Incidence Rates          3141 non-null   object
 8   Lower 95% Confidence Interval.1                     3141 non-null   object
 9   Upper 95% Confidence Interval.1                     3141 non-null   object
dtypes: int64(1), object(9)
memory usage: 245.5+ KB

In [76]:
incd.columns

Index(['County', ' FIPS', 'Age-Adjusted Incidence Rate(Ê) - cases per 100,000',
       'Lower 95% Confidence Interval', 'Upper 95% Confidence Interval',
       'Average Annual Count', 'Recent Trend',
       'Recent 5-Year Trend (ˆ) in Incidence Rates',
       'Lower 95% Confidence Interval.1', 'Upper 95% Confidence Interval.1'],
      dtype='object')

In [77]:
cat_cols = ['Age-Adjusted Incidence Rate(Ê) - cases per 100,000',
       'Lower 95% Confidence Interval', 'Upper 95% Confidence Interval',
       'Average Annual Count', 'Recent Trend',
       'Recent 5-Year Trend (ˆ) in Incidence Rates',
       'Lower 95% Confidence Interval.1', 'Upper 95% Confidence Interval.1']
    
incd[cat_cols].apply(get_unique_vals)

Unique Values in Column Age-Adjusted Incidence Rate(Ê) - cases per 100,000 are:  [62.4 74.9 66.9 74.6 86.4 69.7 65.8 58.3 84.2 75.4 82.4 73.9 49.2 69.5
 83.3 71.5 75.9 73.5 82.6 83 61.5 69.6 76.7 76.2 60.8 78.1 75.5 81.9 77.3
 72.4 90.3 87.9 71 66.5 70.8 80.9 65.1 80.4 69.3 88.1 59.4 73.4 57.6 57.9
 64.8 61.6 74.2 79.4 62.3 61 83.1 65.6 61.8 78.7 74.7 57.1 55.5 74 70.5
 72.3 98.3 74.8 73.2 90.8 '* ' 62.7 58.1 35.1 64.9 88.3 103.6 153.4 67.6
 81.4 44 76.8 66.1 78.8 22.9 46.9 36.7 54.3 45.5 64 54.4 52.2 76.6 39.6
 50.9 36.1 51.9 48 85.9 77 85.6 56.4 67.7 86.3 82.5 59.1 76.4 71.6 108.7
 83.6 77.5 72 75 79.1 75.6 82.2 79.2 77.1 64.7 80.6 96.1 89.2 60.6 94.2
 96.2 82.3 55.9 104.4 97.5 97.2 98.1 102.7 57 63.4 79.5 87 91.9 67.8 82.7
 81.2 73.6 89.5 67.5 69.2 63.9 84 98.8 87.8 114 67.1 89 68 83.9 65.2 91.5
 72.1 78.2 70.4 89.3 91.2 108.5 46 58.7 61.4 52.3 56 78.4 50 50.8 61.2
 44.3 45.7 55.7 48.8 73.7 60.9 39.9 51.8 41.6 54.6 56.9 43.7 24.6 42.6
 53.3 47.3 44.1 49.6 44.2 47.2 40.2 49.5 49 56.8 45.3 42.1 41.1 37.6 62.5
 60.5 57.4 56.3 66.6 47.9 58 41.5 42.3 68.1 52.6 47.5 31.7 35.5 48.4 36.9
 38.1 34.7 59.5 46.3 48.5 37.1 28.3 50.3 43.2 24.8 59.2 55.1 34.4 39.7
 53.5 36.4 56.1 40 40.5 35.8 53 24.1 67.3 49.8 29.2 31.5 14.8 54.9 62 65.7
 70.2 68.7 65 59 99.5 88.4 82.1 79.7 43.3 88.2 57.7 100 93.4 66.4 74.3
 92.6 69 73.3 71.2 67 42.5 97.3 76 54.8 103.5 82 59.6 44.4 71.8 93.3 54.7
 54.1 68.9 74.4 64.5 54.2 65.3 87.2 84.4 203.7 95.9 87.5 72.9 89.6 91.3
 76.9 84.3 78.6 95.7 67.4 82.9 60 101.5 64.1 86.9 60.3 90 100.7 74.1 53.2
 81.3 58.6 81.1 85.2 68.8 47.4 54.5 76.1 71.9 94.7 69.9 64.4 38.8 94.4
 104.6 83.4 62.8 68.6 65.4 79.9 86.5 77.2 83.2 88.9 55 90.4 64.6 66.8 89.1
 85.1 72.7 71.7 65.5 103.1 70.3 78.9 46.8 77.7 77.9 80.1 102 50.6 110.8
 56.6 60.7 63.1 100.8 63 74.5 71.4 78.5 71.1 91.8 67.9 70.6 84.9 68.2 69.8
 77.6 66 44.9 48.3 45.2 41 79 38.7 22.6 35.7 34 55.4 52.4 40.4 48.2 33.9
 46.5 40.7 41.4 98.7 53.4 41.3 68.3 93.5 66.3 54 89.7 94.1 63.6 72.8 94.3
 88.7 103.4 92.7 58.9 69.1 58.2 81.6 90.7 96.6 83.5 58.5 92.3 100.9 66.7
 79.8 68.4 105.5 113.1 75.8 63.8 91.6 50.2 61.9 77.8 73.8 94.6 68.5 87.4
 79.3 83.8 70 85.5 46.7 81.7 97.9 81.8 75.3 123.2 85.4 85 75.1 101.2 95.1
 80.8 84.7 79.6 64.3 42.4 72.5 61.3 82.8 40.9 45.4 47.6 52.9 57.8 53.6
 38.4 86.7 59.9 63.7 48.7 55.6 58.8 41.9 50.5 60.1 73.1 52.1 98 61.1 84.6
 43.4 46.1 43.1 36 '_ ' 106.9 109 86 120.6 105.7 110.2 90.9 103.9 94.5
 95.2 120.7 103 108.6 118.6 111.7 96.4 124.6 90.5 149.4 93 112.4 104 97.8
 95.8 85.8 129.7 107.4 127.6 114.5 109.3 80 89.9 118.3 113 116.1 125 113.9
 117.7 151.8 118.5 112.6 98.5 157.5 101.7 109.7 145.1 123.7 118.1 107.7
 106.8 94.8 98.9 102.6 106.5 124.8 148.1 139.7 123 152.9 93.6 111.8 92.4
 102.4 87.3 84.8 100.2 113.2 106.4 80.5 109.1 122.4 80.7 92.2 70.9 87.6
 78.3 97.4 80.3 91.7 92 84.1 52.7 35.4 46.6 51.1 53.7 52.5 52.8 '66.2 #  '
 '48.6 #  ' '53.7 #  ' '77.1 #  ' '59.1 #  ' '104.9 #  ' '74.9 #  '
 '45.3 #  ' '60.7 #  ' '71.4 #  ' '69.7 #  ' '61.6 #  ' '71.1 #  '
 '56.1 #  ' '61.7 #  ' '73.6 #  ' '75.6 #  ' '36.6 #  ' '73 #  '
 '63.2 #  ' '50.7 #  ' '51.8 #  ' '63 #  ' '80.3 #  ' '79 #  ' '63.1 #  '
 '66.4 #  ' '66 #  ' '62.4 #  ' '49.6 #  ' '56.8 #  ' '58.8 #  '
 '63.5 #  ' '65.6 #  ' '60.4 #  ' '69.2 #  ' '82 #  ' '61.3 #  '
 '73.4 #  ' '59.3 #  ' '77.4 #  ' '71.9 #  ' '35.7 #  ' '60 #  '
 '54.6 #  ' '84 #  ' '61.9 #  ' 75.2 '67.3 #  ' '64.9 #  ' '54.9 #  '
 '69.4 #  ' '50.1 #  ' '58 #  ' '73.3 #  ' '63.6 #  ' '75.3 #  '
 '78.6 #  ' '77.6 #  ' '63.8 #  ' '51.2 #  ' '73.2 #  ' '97 #  '
 '87.3 #  ' '68.2 #  ' '39.3 #  ' '57.9 #  ' '81 #  ' '69.1 #  '
 '69.5 #  ' '65.7 #  ' '50.2 #  ' '70.8 #  ' '77.9 #  ' '73.5 #  '
 '54.4 #  ' '90.7 #  ' 75.7 76.3 86.2 78 49.9 95 95.6 62.9 106 55.8 90.6
 114.7 95.3 90.1 77.4 67.2 86.8 70.1 110 93.1 39.5 100.1 100.3 103.3 76.5
 87.7 60.4 114.1 88.8 112.7 88.6 59.8 92.9 92.8 64.2 99 114.9 52 58.4 97.1
 42.8 85.3 48.9 62.1 49.3 66.2 32.5 45.9 73 43.8 63.3 48.1 59.3 57.3 42.2
 29.3 36.8 '__ ' 72.6 53.8 39.4 41.2 44.7 26.5 13.5 34.8 55.2 37.3 47.8 35
 50.4 61.7 89.8 72.2 71.3 81 96.9 56.5 57.5 85.7 84.5 95.5 51.4 59.7 43.5
 42.7 56.7 40.6 53.9 87.1 106.2 86.6 65.9 55.3 70.7 69.4 48.6 56.2 114.2
 80.2 60.2 88.5 62.2 51.3 63.2 53.1 43.9 45.6 62.6 47 51 81.5 96 49.4 38.6
 45 46.4 104.7 105.9 96.8 99.2 102.8 88 100.4 102.9 83.7 98.6 63.5 98.2
 93.8 116 109.2 101.4 45.1 44.5 50.7 32.2 32.9 39.2 32.7 51.7 42 99.4 38.5
 49.7 44.8 30.3 38.2 20.4 15.8 25 29.5 32.6 25.8 32.1 18.2 27.6 18.5 34.5
 29.7 33.6 91.1 37.2 57.2 40.8 51.2 32 28.8 107.3 167 110.1 100.5 127.9 37
 47.7 41.7 99.8 111.5 115.7 51.5 41.8 46.2 36.3 23.7]




Unique Values in Column Lower 95% Confidence Interval are:  [62.3 65.1 62.4 61.8 71 61.2 47.3 46.4 77.5 64.4 69.8 63.7 36.3 57.3 65.8
 58.1 67.2 57.1 63.9 72.3 46.3 62.6 66.7 65.6 53.5 69.7 64.8 75.1 60.7
 77.2 65 55 52.7 64.2 71.7 62.5 64 62.9 75.6 53.2 65.7 41.1 45.3 61.1 49.3
 63.1 72.1 71.9 50.2 56.5 74 52.8 50.5 62.2 68.8 67.1 52.2 40.5 66.5 61
 66.9 89.2 58.9 54.4 76.9 '*' 40.3 49.1 24.8 55.4 48.8 60.6 68.4 95.2 37.1
 48.2 26.6 48.1 51.9 33.2 18.1 42.5 31.5 47.7 36 44.1 51.2 72.6 34.5 42.7
 29 48.6 70.1 63.3 76.4 52.1 58 66.3 56.2 48.9 58.3 57.8 90.6 72 56.6 58.8
 61.4 70 64.9 62 60.1 49.4 74.2 78.1 77.8 48.4 81.6 76.2 70.9 43.1 86.5
 88.3 81.9 73.9 85.3 40.2 46.7 72.9 81.8 52.6 68.6 70.3 63.2 67.3 46.1
 72.4 67.5 97.9 54.9 76.7 68.2 67.4 71.5 71.6 53.9 51.1 52.4 82.5 80.9 73
 44.5 45.1 42.2 47.4 65.2 45.9 49.5 39.8 35.2 43 66 39.3 46.6 38.5 43.2
 52.3 29.4 13.6 39.7 48.5 55.1 32.2 48 47.9 46.9 54.1 43.6 43.3 39.4 34.2
 52.5 54.8 49.9 57.6 51.3 44.8 51 39.5 38 59.2 33.3 44.9 20.8 25.8 32.3
 39.9 27.5 21.1 34.8 38.1 45.8 19.1 34 34.6 30.3 13.5 41.3 36.4 36.6 31.6
 27 26 41.6 39.1 23.5 32 14.3 45.5 18.6 19.9 35.9 7.6 41.7 52.9 59.9 60.9
 67.8 64.7 73.5 64.3 69.9 56.3 83.1 82.7 69 61.3 58.4 74.9 73.6 40.9 79.4
 83.2 75.4 74.3 73.2 59.1 41.8 75.2 56.1 70.6 67.7 67.6 41 30.6 70.7 92.5
 49.2 42.4 78.7 55.6 73.4 81.7 55.5 50.7 67 71.8 88.9 60.8 69.1 55.2 60
 76.8 172.4 80.8 61.5 38.3 40.7 63 79 82.9 54.5 70.2 76.1 43.4 48.7 86
 36.9 59.5 77.9 58.5 59.8 66.1 65.9 73.3 44.3 59.7 54.2 49.6 41.9 73.8
 64.6 83.6 55.8 24.9 80.3 57.4 81.4 62.1 68.7 59.6 46.2 66.6 69.3 54.6
 60.3 51.6 76.3 43.5 53.8 62.8 89.1 58.2 59 89.3 69.5 53.4 37.8 53.1 61.6
 51.8 50 84 36.5 41.4 60.5 57.9 75.7 57.5 44.7 56.9 46.5 38.9 39 31 14
 30.5 24.1 27.1 53.6 50.9 37.2 23.6 35.6 40.1 42 26.7 52 23.9 80.1 26.8
 55.3 56.8 59.4 57.2 82 60.2 53.7 70.5 46 91.8 78.4 63.5 60.4 55.7 77.4
 89.5 44.4 74.7 50.4 66.4 42.9 78.6 54.3 83.3 61.7 71.3 72.5 64.1 81 63.6
 51.4 57.7 47.5 77.7 80.6 72.2 57 77.1 69.4 42.6 74.1 54.7 72.8 82.6 65.3
 70.8 79.1 74.8 58.7 91.2 83.8 50.8 68 76.5 44.6 75.3 41.5 28.7 26.3 30.1
 33.5 47.6 45.4 27.9 76 53.3 39.2 69.2 27.8 35.5 53 50.6 43.8 54 80.4 44
 35.7 77 32.7 27.7 42.1 38.7 51.7 42.8 64.5 28.9 '_' 74.5 94.9 86.3 85.5
 82.4 91.9 84.6 92.7 81.2 83.9 66.8 94.7 88.1 89.4 80.7 99.2 56.7 71.4
 101.9 102.7 71.2 134 82.2 84.5 79.7 74.6 112.6 94.8 92.8 111.5 78.9 95.8
 88.8 79.5 95.5 86.7 95.9 83.7 95 109.6 79.2 93.3 87.6 124.3 101.6 90.9
 83.5 88.7 133.1 117.3 103.4 100.2 92.3 84.1 84.2 79.6 78.3 107.4 68.9
 107.8 122.2 112.1 125.7 75.5 85 65.4 87.3 85.1 63.4 84.8 87.8 107.5 61.9
 63.8 55.9 46.8 45.2 35.4 81.1 69.6 56 40.4 49 33.8 66.2 45.7 35.1 34.1
 48.3 50.3 47.1 58.6 47.2 72.7 59.3 78.2 29.1 75 32.9 31.4 68.5 31.7 37.6
 93.2 79.8 75.8 78.8 84.7 56.4 86.8 85.2 80.5 73.1 62.7 31.1 86.1 80 94.5
 50.1 77.3 88.4 70.4 96.7 78 95.3 68.1 26.5 23.7 44.2 30.9 36.1 33.7 32.6
 28.8 20.2 21.6 34.7 29.8 34.4 49.8 32.1 34.9 39.6 45.6 29.7 37.7 32.4
 25.6 16.6 25.5 '__' 68.3 47 37.4 24 40.8 27.6 9.7 38.8 28.1 35.3 86.4
 78.5 65.5 67.9 71.1 51.5 47.8 35.8 29.9 22.6 32.8 94.1 28.5 81.3 43.7
 76.6 37.5 37.3 28 31.8 43.9 40.6 77.6 36.8 25.3 27.2 38.6 26.9 41.2 26.1
 24.5 38.2 29.5 87.1 94 87.7 92.6 93.6 87.4 97.1 85.6 73.7 83 38.4 19.3
 31.3 26.4 36.2 45 23.8 30.7 28.3 29.2 27.3 25.9 22.9 36.7 33.1 42.3 15 12
 22.1 22.3 19 15.2 30.4 21.3 11.4 16.3 22.7 26.2 37 24.3 40 24.4 98.7
 128.5 28.2 98.6 87.5 102.8 24.6 33.9 30 75.9 82.3 102.2 22 28.4 14.7]




Unique Values in Column Upper 95% Confidence Interval are:  [62.6 85.7 71.7 89.4 104.2 79 89.6 72.7 91.3 87.9 96.9 85.4 66 83.7 104.5
 95.4 81.9 85.5 93.8 106 95.1 80.6 77.3 87.7 88 68.9 87.2 87.6 89.1 95.3
 85.8 105.2 117 90.6 83.3 77.8 91.1 67.8 100.3 76.3 102.3 66.1 81.8 73.3
 68.6 76.4 86.9 79.1 76.7 65.6 87.4 108.8 81 74.9 91 83.1 62.2 74.7 82.1
 81.3 78.1 108.1 93.9 96.7 106.7 ' *' 66.8 91.9 68 47.9 75.4 115.9 108.2
 79.7 148.9 229.4 111.2 128.5 68.5 116 99.9 115.6 28.5 51.8 42.4 61.7 56.7
 92.5 67.2 53.2 80.9 45.2 52.7 48.5 44.4 55.3 52.1 104.4 92.9 95.9 60.9
 78.8 111 118.7 71.1 99 87.8 129.9 97 87.3 82.7 87.5 110.8 101.5 95.6 84
 94.8 84.2 117.2 101.9 75.2 108.5 120.1 95 72.2 125.2 107.5 114.5 128.9
 123.1 84.4 101.1 103.3 102.9 86.5 99.7 93.4 85.3 118 90.2 94 125.7 106.3
 112.7 132.3 81.6 116.7 102.5 79.8 80.8 116.1 97.1 85.2 90.5 107.3 72.8
 100.7 143.6 105.7 47.6 68.1 65.8 60.5 51.1 93.6 54.3 53.1 49.3 58.8 58.4
 55 82.2 75 40.5 57.3 44.8 68.8 58.6 63.8 40.8 45.7 52.6 56.4 58.7 49.5
 50.1 51 59.6 50.3 47.5 44.9 42.5 41.2 69.6 61.6 52.2 60.6 63.4 73.7 51.3
 65.7 43.6 47 56.2 66.7 123.4 71.5 39 58.1 63.7 100.8 56 51.2 41.4 40 64.5
 65.3 70.4 46.2 80.5 43.1 62.4 48.2 61.3 50.8 61.8 53.5 52.8 85.6 38.1
 89.8 54.5 44.3 96.1 25.7 55.9 50 57 64.2 67.1 70.8 72.5 72.9 71.6 78.7
 61.9 118.2 94.3 76.8 54.9 98.7 66.6 84.8 85 45.9 97.7 119.8 76.9 113.4
 88.3 77.9 79.5 79.3 71.8 71.9 56.8 58 130.8 79.6 61.4 59.3 115.7 70 62.1
 63.9 45.4 89.7 77.1 106.1 59.8 58.9 55.6 77 106.2 69.9 81.1 60.2 71.2
 98.8 101 239.1 73.6 113 83.8 90.1 88.2 114.2 122.3 100.4 103.8 96.8 94.4
 108.6 96.3 89.9 104.6 114.4 97.4 80.1 92.3 74.5 133.9 119 69.8 108.7 71
 123.5 63.3 92.7 68.3 111.5 72.1 127.3 99.4 99.2 78 81.5 98.3 83.4 93.1 89
 97.6 79.9 106.9 54.7 74.8 110.4 82.6 132.6 80.2 110.2 102.1 97.8 80.3
 95.2 106.8 102.6 92.2 73.1 87.1 86 106.6 92.8 124.1 102.7 82.4 75.9 59.1
 96.4 86.1 99.3 90.3 174 78.2 69.1 110.6 91.5 104.9 120 89.2 80.7 112.2
 109.2 121.1 84.1 76.2 122.1 84.9 83.2 88.4 105.3 49 50.2 52.3 47.8 55.7
 110.1 48 105.5 34.4 103.1 64 41.6 46.6 77.6 58.2 83.6 62.3 46.8 63 67.7
 105.4 70.5 66.9 90.7 123.6 88.1 117.1 81.2 119.5 69.4 112.8 107.6 100.2
 64.4 81.4 115 58.3 72.4 116.3 86.7 102.8 112.9 131.6 107.1 84.6 79.4 91.6
 105.8 94.7 68.2 61 78.6 105.6 70.2 104.1 76.5 113.3 122.4 97.9 94.6 100.9
 74.3 154.1 151.5 91.8 100.6 82.9 119.4 92.4 109.1 122.9 115.5 92 93.5 108
 75.3 107.4 78.3 61.5 86.6 111.3 96 122.2 75.7 65.1 75.6 103.4 88.5 82.5
 87 93.3 100 95.7 115.4 74.2 84.3 77.5 73.8 81.7 95.5 164.2 121.4 86.3
 109.3 98 76.1 109.4 93.7 110.7 83.5 111.8 70.3 113.1 112.5 90.9 91.2
 110.3 67.3 100.5 54.6 60.8 52 98.6 75.1 66.3 73.9 107 57.2 85.1 70.6 86.2
 83 69 76.6 79.2 56.9 53.9 66.5 93 74 ' _' 101.4 114.8 124 120.2 136.1
 115.3 112.1 103.9 91.7 155.8 130.7 130.4 111.4 127.8 103.7 133.6 151.8
 131.1 95.8 107.7 140.8 140.3 128.7 119.2 108.9 150.2 113.7 166.1 104.8
 147.9 141.2 119.1 98.4 148.8 121.5 145.5 133.4 116.9 145.1 97.3 140.6 142
 138 155.3 184.1 137.5 138.2 142.2 90 185.2 137.3 121.9 177.5 147.2 138.3
 165.5 111.1 136.3 134.2 124.2 117.8 144.4 199.8 122.6 159.1 134.7 184.6
 103.5 181.8 141.5 111.9 128.8 117.4 107.2 147.7 131.9 99.8 120.7 138.9
 155.5 73.4 123.2 120.8 94.2 77.4 121 70.7 90.4 84.7 80.4 114.1 82.8 73.5
 88.9 72 86.8 94.9 104 88.6 102 69.5 77.7 60.3 67.4 73 88.8 37.1 48.9
 113.2 78.9 63.6 57.8 63.5 72.3 68.7 52.9 64.8 42.9 91.4 57.7 74.6 83.9
 92.6 67 63.2 77.2 69.2 101.8 114 42.8 109.5 124.6 101.6 116.5 110 71.3
 73.2 132.2 97.2 103.6 101.7 103 115.8 67.5 117.7 140.2 66.2 102.4 106.5
 120.9 107.8 78.5 149.1 98.1 128.1 109.7 115.1 74.1 94.5 117.6 93.2 129.7
 105.1 113.9 163.9 123.8 133.8 66.4 90.8 131.2 101.3 112.6 107.9 138.1
 53.4 111.7 43.9 167.6 104.7 57.6 76 59.5 50.9 82 108.4 99.5 64.6 98.5
 55.5 56.5 48.7 51.9 ' __' 63.1 53.3 51.5 70.1 50.6 55.1 56.6 46.7 38 18.3
 43.5 45.5 49.7 47.7 35.7 70.9 44.1 85.9 60.1 53.6 84.5 74.4 60 65.4 120.5
 110.9 86.4 64.1 62.8 143.1 58.5 69.3 117.9 61.1 54.8 68.4 102.2 72.6 57.9
 103.2 65.5 67.6 49.8 62.7 88.7 59.2 119.9 89.3 125.8 121.3 100.1 120.3
 108.3 64.9 56.1 65.2 57.1 65 65.9 56.3 67.9 75.8 59 62.5 89.5 78.4 154.8
 71.4 135.3 94.1 148.6 147.4 118.9 112 105.9 118.8 113.8 101.2 126.9 118.4
 128.4 106.4 142.9 123.3 137.9 129 136 51.7 105 34.9 64.3 46.1 55.8 139
 98.2 34.8 53.7 55.2 57.5 46.9 109.6 62 47.2 109.9 49.4 43.7 54.2 34.2 53
 27.1 20.3 28.2 38.3 41.1 34 42.1 27.5 38.2 20.8 33.5 37.4 126.2 41.8 98.9
 41.9 49.1 45.1 42 33.8 146.7 132.4 214.5 36.9 157 151.1 129.2 116.4 158.2
 54.4 62.9 52.5 130.5 120.6 131 130.6 96.5 75.5 122.8 130.1 59.9 47.3 69.7
 45.6 36.1]




Unique Values in Column Average Annual Count are:  [214614 43 170 25 23 51 9 17 120 34 32 39 10 16 14 57 44 11 73 66 36 110
 19 28 35 88 58 482 87 37 71 69 8 15 236 33 90 347 144 116 18 22 24 47 72
 108 74 41 135 89 31 '3 or fewer' 131 6 12 7 3 4 5 84 52 2059 280 46 628
 201 203 115 21 129 13 26 38 56 78 121 45 29 27 62 30 59 277 20 100 119 81
 687 169 554 411 86 371 54 70 3701 76 145 163 92 75 1326 222 1031 793 807
 1485 459 353 161 375 189 705 99 154 246 288 273 174 344 182 253 94 264
 282 262 124 102 101 571 662 160 718 224 98 147 387 239 351 185 647 1129
 233 244 268 77 685 281 241 155 895 180 400 651 130 67 328 493 177 1310 83
 153 48 588 1183 552 1032 631 106 166 479 53 568 55 91 134 50 183 341 311
 431 96 42 148 49 61 79 107 550 80 191 68 3359 63 529 266 379 113 40 97
 140 265 127 219 151 414 85 252 227 65 64 412 103 133 682 212 152 309 '_'
 93 206 104 759 240 60 340 242 126 179 237 187 82 364 661 117 184 118 361
 512 247 476 602 368 511 430 448 616 143 399 157 756 866 105 173 141 172
 1634 178 111 220 542 109 195 854 275 338 '__' 283 230 580 342 406 136 122
 250 279 235 475 287 645 276 171 274 258 641 226 886 1218 569 992 892 245
 432 248 1161 188 1195 164 615 211 202 367 452 158 95 285 139 181 1108 736
 673 149 259 306 232 123 507 128 449 156 513 421 231 1193 192 316 487 301
 210 468 225 208 271 308 249 1260 150 503 142 257 324 286 196 424 357 587
 200 702 175 1078 1768 903 330 260 390 190 125 972 590 433 313 137 658]




Unique Values in Column Recent Trend are:  ['falling' 'stable' '*' 'rising' '_' '__']




Unique Values in Column Recent 5-Year Trend (ˆ) in Incidence Rates are:  [-2.5 0.5 3 -6.4 -4.5 -13.6 7.2 2 -3.8 -7.9 7.1 -0.2 9.7 -1.3 -13.8 4.8
 -7.2 -4.4 -9.7 -11.5 5.7 14.7 -2.2 -3.2 7.4 -2.1 -3.4 0 -0.1 -6.1 -2.7
 10.2 1.8 -14.3 -2.3 -2.6 -1.8 4.1 -9 0.3 -14.5 -4.6 0.1 1.2 -5.3 -8.5
 -9.6 -5 -13.2 -11.9 -3.6 2.5 -4.1 -0.5 -6.2 -12.5 '*' -6.5 -26.1 -8.4 3.5
 -12.8 -16.9 -19.2 -15.3 0.2 -6.6 34.9 4.4 -9.8 -17.3 13.4 0.9 -10.5 -5.2
 -7.1 -5.7 -4 -0.7 -1.1 -16.4 -3.7 -4.3 -6.8 6.2 1.3 6.5 11.9 5.1 -1.4 8
 2.1 15.8 8.8 -12.9 4.5 -0.6 7.8 -18.2 -11.7 -0.8 -1.2 5 5.6 -0.4 6.6 -0.3
 -4.8 -1 -7.7 -11.1 6.4 -11 -15.4 2.2 2.6 18.8 17.7 3.3 1.6 12.4 -6.9 -1.5
 4.3 1.1 9.4 10 -1.9 3.2 3.9 6 8.7 -14.6 -3.1 -15.5 -9.2 -1.6 -10.2 -7
 -19.5 -2.8 -13.3 -3.5 -5.9 -17.4 -11.2 -8.1 -2.4 -6 -22 -4.9 21.1 -13.5
 14.1 -1.7 -16.2 10.8 -16.7 9 -6.7 -10.3 -12.4 -26 -30.6 25.9 -7.5 -32.9
 -4.7 -5.4 -4.2 0.8 -2.9 -6.3 -10 1.9 15.5 1.7 0.4 5.2 3.4 -13.9 10.1 -2
 0.7 4.7 -7.4 1.4 -7.6 5.9 15 23.9 9.1 11.6 9.2 -3.9 17.8 -5.6 1.5 14.9
 -10.4 2.9 8.3 0.6 -7.3 11.1 15.3 27.9 2.4 -20.2 -19.3 -11.4 -23.1 -10.1
 13.1 8.5 -5.1 -18.3 8.6 19.6 5.4 12.5 19.8 3.7 12.7 6.1 1 15.7 -13.1 6.3
 -17.2 9.3 -8.3 6.9 -8.2 -8.9 -5.8 22.4 -9.3 -8.7 12.6 4.2 -8 -3 -14.7
 17.5 -10.7 -5.5 2.3 -8.6 18.9 2.7 27.1 22.9 5.3 -12 -15.8 -18.6 10.9 -0.9
 -14.2 7.6 12 16.2 -7.8 5.8 3.6 11 5.5 19 -11.3 -9.5 18.1 3.1 6.8 -28.4
 '_' -19.6 14.3 2.8 12.3 17.9 9.6 -3.3 -9.1 11.3 3.8 10.6 -15 8.2 -10.8
 -14.8 -9.4 -8.8 7 -15.2 6.7 16.3 9.8 18.3 36 15.2 -12.1 10.3 4 -12.6
 -12.7 -25.7 -13 -18.5 -14.1 13.5 -19.9 -13.4 11.8 -10.6 13.7 14.8 8.4 4.9
 7.5 -17 -21.5 10.4 8.1 27.6 11.7 20.4 -11.6 37.5 -11.8 -19.1 7.3 12.8
 -32.5 38.6 17.1 14.4 -23.7 15.9 12.1 20.9 35.3 19.4 32.1 16.5 '__' 13
 -12.2 10.7 16.6 22.3 13.3 7.9 -29.1 -17.1 22.2 18.5 -24.5 -19 -15.7 16.8
 22.5 -16.5 -24.1 -9.9 28.4 -20.7 11.4 17.3 25.4 4.6 12.9 -10.9 11.5 -14.4
 26.3 -16.1 -25.8 -22.2 17.4 -38.6 20.5 -25.4 -17.9 -28.1 20 -40.1 20.1
 44.2 34.7 -19.4 40.9 38.5 29.3 -20.5 31.7 19.3 13.8 39.6 8.9 -26.2]




Unique Values in Column Lower 95% Confidence Interval.1 are:  [-3 -14.9 -10.2 -18.3 -31.4 -27.8 -27.6 -10.7 -13.9 -8.5 -13 -17.6 -12.4
 -30.7 -20.1 -20 -15.6 -41.4 -43.5 -11.2 -21.8 -20.4 -11.4 -16.9 -11.9
 -21.5 -9.8 -36.5 -18.9 -16.1 -28.3 -25.5 -24.3 -6.7 -14.7 -3.3 -14.5 -8.2
 -4.6 -11.3 -42.7 -37.2 -7.2 -9 -12.5 -12.6 -6.5 -26.5 -15.1 -12 -20.5
 -26.2 -35.2 -15.4 -6.9 -15 -30.3 -1.9 -12.1 -9.9 -23.4 -24 -23.7 '*'
 -12.8 -50.8 -19.1 -12.3 -26.4 -32.5 -36.4 -9.7 -54.8 -34.3 -36.7 -6.6
 -40.6 -32.9 -48.3 2.4 -4.7 -26.6 -24.4 -31.1 -31.5 -27.3 -5.5 -12.7 -7.4
 -9.5 -48 -17.5 -14.3 -10.4 -11.8 -4.2 -11.7 -25.1 -5.8 -40 -18 -10 -24.9
 -17 -29.1 -8.8 -3.7 -25.2 -45.5 -32.8 -4.9 -38.4 -25.9 -27.9 -4.5 -14.8
 -14.4 -23.1 -22.2 -10.9 -17.2 -7.7 -29.6 -42.6 -17.9 -20.2 -23.5 -24.7
 -4.1 -21.7 -25.4 -28.6 -5.1 -16.3 -11.1 -16.6 -16.5 -42.5 -8 -4.3 -15.5
 -20.3 -33.5 -0.5 -10.6 -8.1 -9.1 -31 -13.5 -2.5 -27.5 -43.3 -1.6 -39.3
 -11 -6.3 -28.7 -6.8 -17.1 -9.2 -7 -2.2 -32.6 -12.2 -15.3 -10.3 -23.8 -8.4
 -6.2 -26.7 -5.4 -2.6 -15.8 -4.8 -12.9 -21.6 -35.6 -22.8 -5.3 -35.1 -39.6
 -26.9 -29.8 -34.4 -41.9 -37.4 -32.2 -5.2 -23 -40.8 -28 -62.9 -22.3 -33.4
 -19.6 -17.7 -41 -28.1 -49.6 -51.1 -47.5 19.4 -8.7 -19.5 -29.2 -66.6 -15.2
 -1.2 -0.6 -0.9 -1.1 -1.3 -6 -19.8 -6.1 -35.4 -18.6 -17.8 -16.8 -7.8 -39
 -22.7 -22.4 -2.3 -29.4 -3.4 -8.3 -7.1 -13.7 -39.2 -2.8 -7.5 -13.1 -5
 -14.1 -9.3 -3.1 -6.4 -18.1 -7.6 -39.8 -13.6 -1.4 -34.6 -20.7 -32.1 -35
 -5.9 -11.5 -14.2 -21.9 -1.7 -40.1 -13.3 -26.1 -22.9 -33.2 -17.3 -18.4
 -10.1 -32.3 -38.8 -16.4 -14.6 -16 -1.8 -14 -11.6 -2.1 -31.7 -22.1 -45.3
 -29.3 -23.9 -36.2 -36.6 -2.4 -35.3 -22.5 -35.7 -28.8 -54.5 -25.6 -13.8
 -36.8 -30.5 -45.2 -20.8 -13.4 -21 -18.7 -34.1 -44.9 -30.4 -36.9 -21.1
 -24.6 -19.3 -18.8 -16.7 -9.6 -21.2 -48.6 -23.6 -44 -34.2 -44.2 -52.1
 -37.9 -41.5 -24.1 -38.2 -34 -43.6 -29.5 -7.9 -47.4 -39.4 -15.9 -26.3
 -25.7 -27.1 -22.6 -30.1 -9.4 -27 -45 -7.3 -37.3 -16.2 -21.3 -8.9 -37.5
 -8.6 -27.7 7.2 -26.8 -46 -25.8 0.3 -36.1 -29 -0.4 -17.4 1.9 -34.5 -20.9
 -43 -4.4 -25.3 -27.2 -33.6 8.2 -38.1 -0.7 -4 0.1 -1.5 -0.8 -2.7 0.9 -2.9
 -2 -0.3 -3.2 -1 0.5 -3.8 '_' 2.7 -28.9 -49.7 -19.7 -19.9 -32.4 -59.1
 -23.2 2.2 -20.6 -53.2 -24.8 -18.5 -38.6 -22 -29.9 -10.8 -3.5 2 -13.2
 -29.7 -3.9 -0.1 -5.7 -43.1 -38.5 -33.8 -25 -38.9 -24.2 -28.4 -46.1 -54
 -15.7 -10.5 -21.4 -35.9 -19.4 -31.6 3.7 -34.8 0.6 9.3 -33.3 -18.2 -38
 -46.6 -52.3 -28.2 -35.8 1.1 5.9 5.2 -48.9 -44.8 12.8 -19.2 -30.9 -55.9
 10.9 -37.1 -46.8 -47.8 -44.1 -53.5 -63.6 19.1 -40.9 -51.2 -49.8 -56 -24.5
 -36 -36.3 -33.7 -52.8 8.1 -43.2 -45.6 '__' 3.6 -5.6 0.8 -3.6 3 -43.7
 -28.5 -27.4 0.7 -50.1 4 -31.8 -50.3 -37 -31.2 -41.2 -33 -49.9 -30.2 -34.9
 -39.1 -51.7 -33.1 -42.9 -32.7 -45.4 -41.8 -40.4 -46.9 -60 -51 -53.6 -57.1
 5.5 -23.3 -49.5 -34.7 -62 -48.4 -41.3 -32 -26 -56.8 -47.3 -59 -42.4 -53.7
 -41.7 -69 -30.8 -40.7 -35.5 -48.1 -31.3 -68.2 -50.2 -42.1 3.9 -64.6 -38.7
 -39.9 -47 -48.2 4.1 10 2.9 -38.3 -65.4]




Unique Values in Column Upper 95% Confidence Interval.1 are:  [-2 18.6 18.3 7.3 32.9 3.4 58.7 16.6 7.5 -7.3 31.7 20.8 75.3 11.1 7.2 37.4
 7.6 8.3 39.2 38.7 25.9 68.4 20.3 5.7 38.8 8.8 8.4 27.2 10.6 15.6 12.8
 69.3 39 -2.9 2.2 11.3 -0.3 26.6 6.1 15.3 5.6 6.6 27.6 40.5 -1.9 10.1 17.1
 2.6 2.4 13.9 -3.8 6.4 13.6 2 19.8 16 9.7 2.5 3.8 37.1 7.1 3.7 11.2 29.2
 15.8 0.4 '*' 0.3 3.6 22.2 2.3 2.7 14.7 58.8 52.7 37.8 94.7 83.3 21.3 32.2
 25.5 6.8 6 30.2 26.1 22.4 -2.4 13 14.9 4.1 -0.6 34.4 4.4 10.9 1.4 25.8
 8.7 23.4 29 67.1 17.2 62.1 42.3 15.9 24.1 78.4 42.5 19.6 12.5 45.9 81.3
 36.2 -0.4 14.8 26.4 24.8 10.8 35.2 15.5 30.8 9.5 32.8 34.7 27.8 44.2 22.6
 -4.5 22.7 12.6 24.6 23 41.3 9.6 16.5 29.3 21.5 15.1 87.5 77 49.6 27.4

Age-Adjusted Incidence Rate(Ê) - cases per 100,000    None
Lower 95% Confidence Interval                         None
Upper 95% Confidence Interval                         None
Average Annual Count                                  None
Recent Trend                                          None
Recent 5-Year Trend (ˆ) in Incidence Rates            None
Lower 95% Confidence Interval.1                       None
Upper 95% Confidence Interval.1                       None
dtype: object

In [78]:
weird_characters = ['*', '_', '__', '__ ', '_ ', '* ', ' _', ' *', ' __', '3 or fewer', '']

def fix_strings(row):
    try:
        row['Age-Adjusted Incidence Rate(Ê) - cases per 100,000'] = float(row['Age-Adjusted Incidence Rate(Ê) - cases per 100,000'].replace(' #  ', ''))
    except:
        pass
    
    for col in cat_cols:
        if row[col] in weird_characters:
            row[col] = np.nan
    
    return row

incd = incd.apply(fix_strings, axis = 1)
incd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3141 entries, 0 to 3140
Data columns (total 10 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   County                                              3141 non-null   object
 1    FIPS                                               3141 non-null   int64
 2   Age-Adjusted Incidence Rate(Ê) - cases per 100,000  2719 non-null   float64
 3   Lower 95% Confidence Interval                       2719 non-null   float64
 4   Upper 95% Confidence Interval                       2719 non-null   float64
 5   Average Annual Count                                2719 non-null   float64
 6   Recent Trend                                        2672 non-null   object
 7   Recent 5-Year Trend (ˆ) in Incidence Rates          2672 non-null   float64
 8   Lower 95% Confidence Interval.1                     2672 non-null   float64
 9   Upper 95% Confidence Interval.1                     2672 non-null   float64
dtypes: float64(7), int64(1), object(2)
memory usage: 245.5+ KB

In [81]:
incd_clean = incd.dropna()

In [82]:
incd_clean.to_csv('incd_clean.csv', index = False)

### INCD Cleaned!!!

In [83]:
death.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3141 entries, 0 to 3140
Data columns (total 11 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   County                                        3141 non-null   object
 1   FIPS                                          3141 non-null   int64
 2   Met Objective of 45.5? (1)                    3141 non-null   object
 3   Age-Adjusted Death Rate                       3141 non-null   object
 4   Lower 95% Confidence Interval for Death Rate  3141 non-null   object
 5   Upper 95% Confidence Interval for Death Rate  3141 non-null   object
 6   Average Deaths per Year                       3141 non-null   object
 7   Recent Trend (2)                              3141 non-null   object
 8   Recent 5-Year Trend (2) in Death Rates        3141 non-null   object
 9   Lower 95% Confidence Interval for Trend       3141 non-null   object
 10  Upper 95% Confidence Interval for Trend       3141 non-null   object
dtypes: int64(1), object(10)
memory usage: 270.1+ KB

In [84]:
death.columns

Index(['County', 'FIPS', 'Met Objective of 45.5? (1)',
       'Age-Adjusted Death Rate',
       'Lower 95% Confidence Interval for Death Rate',
       'Upper 95% Confidence Interval for Death Rate',
       'Average Deaths per Year', 'Recent Trend (2)',
       'Recent 5-Year Trend (2) in Death Rates',
       'Lower 95% Confidence Interval for Trend',
       'Upper 95% Confidence Interval for Trend'],
      dtype='object')

In [85]:
cat_cols = ['Met Objective of 45.5? (1)',
       'Age-Adjusted Death Rate',
       'Lower 95% Confidence Interval for Death Rate',
       'Upper 95% Confidence Interval for Death Rate',
       'Average Deaths per Year', 'Recent Trend (2)',
       'Recent 5-Year Trend (2) in Death Rates',
       'Lower 95% Confidence Interval for Trend',
       'Upper 95% Confidence Interval for Trend']

death[cat_cols].apply(get_unique_vals)

Unique Values in Column Met Objective of 45.5? (1) are:  ['No' 'Yes' '*']




Unique Values in Column Age-Adjusted Death Rate are:  [46 125.6 125.3 124.9 118.5 113.5 111.1 110.3 109.1 106 104.6 103.5 103.3
 98.7 98.5 97.2 96.5 96.1 95.6 95.3 95.1 94.9 94.6 92.7 92.5 92.3 91.9
 90.8 90.5 90.2 89.6 89.3 89.2 89.1 89 88.9 88 87.9 87.4 87.2 87 86.8 86.6
 85.9 85.4 85.1 84.8 84.5 84.3 84.2 84.1 84 83.8 83.6 83.5 83.1 83 82.7
 82.3 82 81.9 81.7 81.6 81.5 81.4 81.3 81.2 81.1 81 80.8 80.6 80.5 80.3
 80.2 80.1 80 79.9 79.8 79.6 79.5 79.3 79.1 79 78.8 78.7 78.5 78.4 78.3
 78.2 78.1 78 77.8 77.7 77.6 77.5 77.4 77.3 76.9 76.8 76.7 76.6 76.4 76.3
 76.2 76.1 76 75.9 75.8 75.7 75.6 75.4 75.3 75.2 75.1 75 74.9 74.8 74.7
 74.6 74.5 74.4 74.3 74.2 74.1 74 73.9 73.8 73.7 73.6 73.5 73.4 73.2 73.1
 73 72.8 72.7 72.6 72.5 72.4 72.3 72.2 72.1 71.9 71.8 71.7 71.6 71.5 71.4
 71.3 71.2 71.1 70.9 70.8 70.7 70.6 70.5 70.4 70.2 70.1 70 69.9 69.7 69.6
 69.5 69.4 69.3 69.2 69.1 69 68.9 68.8 68.7 68.6 68.5 68.4 68.3 68.2 68.1
 68 67.9 67.8 67.7 67.6 67.5 67.4 67.3 67.2 67.1 67 66.9 66.8 66.7 66.6
 66.5 66.4 66.3 66.2 66.1 66 65.9 65.8 65.7 65.6 65.5 65.4 65.3 65.2 65.1
 65 64.9 64.8 64.7 64.6 64.5 64.4 64.3 64.2 64.1 64 63.9 63.8 63.7 63.6
 63.5 63.4 63.3 63.2 63.1 63 62.9 62.8 62.7 62.6 62.5 62.4 62.3 62.2 62.1
 62 61.9 61.8 61.7 61.6 61.5 61.4 61.3 61.2 61.1 61 60.9 60.8 60.7 60.6
 60.5 60.4 60.3 60.2 60.1 60 59.9 59.8 59.7 59.6 59.5 59.4 59.3 59.2 59.1
 59 58.9 58.8 58.7 58.6 58.5 58.4 58.3 58.2 58.1 58 57.9 57.8 57.7 57.6
 57.5 57.4 57.3 57.2 57.1 57 56.9 56.8 56.7 56.6 56.5 56.4 56.3 56.2 56.1
 56 55.9 55.8 55.7 55.6 55.5 55.4 55.3 55.2 55.1 55 54.9 54.8 54.7 54.6
 54.5 54.4 54.3 54.2 54.1 54 53.9 53.8 53.7 53.6 53.5 53.4 53.3 53.2 53.1
 53 52.9 52.8 52.7 52.6 52.5 52.4 52.3 52.2 52.1 52 51.9 51.8 51.7 51.6
 51.5 51.4 51.3 51.2 51.1 51 50.9 50.8 50.7 50.6 50.5 50.4 50.3 50.2 50.1
 50 49.9 49.8 49.7 49.6 49.5 49.4 49.3 49.2 49.1 49 48.9 48.8 48.7 48.6
 48.5 48.4 48.3 48.2 48.1 48 47.9 47.8 47.7 47.6 47.5 47.4 47.3 47.2 47.1
 47 46.9 46.8 46.7 46.6 46.5 46.4 46.3 46.2 46.1 45.9 45.8 45.7 45.6 45.5
 45.4 45.3 45.2 45.1 45 44.9 44.8 44.7 44.6 44.5 44.4 44.3 44.2 44.1 44
 43.9 43.8 43.7 43.6 43.5 43.4 43.3 43.2 43.1 43 42.9 42.8 42.7 42.6 42.5
 42.4 42.3 42.2 42.1 42 41.9 41.8 41.7 41.6 41.5 41.4 41.3 41.2 41.1 41
 40.9 40.8 40.7 40.6 40.5 40.4 40.3 40.2 40.1 40 39.9 39.8 39.7 39.6 39.5
 39.4 39.3 39.2 39.1 39 38.9 38.8 38.7 38.6 38.5 38.4 38.3 38.2 38.1 38
 37.9 37.8 37.7 37.6 37.5 37.4 37.3 37.2 37.1 37 36.9 36.8 36.7 36.6 36.5
 36.4 36.3 36.2 36.1 36 35.9 35.8 35.7 35.6 35.5 35.4 35.3 35.2 35.1 35
 34.9 34.8 34.7 34.6 34.5 34.4 34.3 34.2 34.1 34 33.9 33.8 33.7 33.6 33.5
 33.4 33.3 33.2 33.1 33 32.9 32.7 32.6 32.5 32.4 32.3 32.2 32.1 32 31.9
 31.8 31.7 31.5 31.4 31.3 31.2 31.1 31 30.9 30.7 30.6 30.5 30.4 30.3 30.1
 30 29.9 29.8 29.7 29.6 29.5 29.4 29.3 29.1 28.9 28.8 28.7 28.6 28.4 28.3
 28.2 27.8 27.6 27.5 27 26.9 26.8 26.6 26.5 26.4 26.3 26.1 25.7 25.6 25.5
 25.4 25.3 25.1 25 24.8 24.7 24.6 24.4 24.3 24 23.9 23.6 23.1 23 22.8 22.7
 22.5 22.2 22.1 21.6 21.3 21 20.7 19.7 18.8 17.7 17.6 17.2 15.8 14.9 14.4
 12.4 11.6 9.2 '*']




Unique Values in Column Lower 95% Confidence Interval for Death Rate are:  [45.9 108.9 100.2 73 83.1 89.9 90.6 87 84.8 76.4 83 88 85.5 86.1 80.3 78.7
 77.6 78.9 61.4 80.7 82.5 81.3 82.8 78.4 79.5 67.4 77.1 64.7 66.4 74.9
 65.2 73.1 73.5 64 70.8 71.8 51.9 72.8 64.2 63.2 69.6 73.9 71 50.3 71.7 76
 68.3 72 67.9 72.1 67.1 70.6 76.2 68.9 64.4 57 57.4 68.5 65.3 63.4 58.8
 68.1 70 65.9 64.6 69.3 67.5 55.2 66.7 64.5 64.8 61.8 62.7 62.6 52.5 61.5
 58.3 65 65.8 69.2 66.8 56.4 60 59.2 55 63.8 60.6 59.3 64.9 51.7 65.1 66
 63.9 71.6 66.1 63.1 68.2 64.1 57.5 58 59 60.7 54.7 68.4 60.2 62.2 62.5
 65.4 59.1 53.4 60.9 66.6 65.5 58.2 67.7 65.7 63.3 56.3 61.1 55.5 43.5
 56.6 60.5 62.1 61.9 43.3 47.9 60.8 56 55.3 58.9 62 61 57.9 59.4 49.7 60.4
 44.9 53.7 62.8 57.6 58.7 61.3 62.3 59.7 51.1 46.2 64.3 50.9 53.6 63.5
 60.3 59.5 57.3 55.7 59.8 54.1 59.9 62.4 48.9 53.2 63.7 55.1 56.8 52.3
 58.1 61.7 52.1 56.9 40.6 57.7 66.5 51 59.6 60.1 63 51.4 50.1 52.9 56.5
 55.8 53.3 54.5 46.6 45.7 53.1 55.6 61.2 43.4 57.8 55.9 50.5 58.4 54.6
 49.2 41.6 53.8 51.2 48 51.6 50.6 53.5 49.4 58.6 49 53.9 52.6 49.6 47.8
 47.2 54 46.7 48.8 53 56.7 52.7 54.2 56.1 46.9 52.8 50.2 46.5 55.4 51.5
 44.6 57.2 50.7 43 61.6 47.5 43.2 54.9 54.3 35.5 48.2 46.3 57.1 47.6 54.4
 50.4 47.7 40.5 58.5 42.1 44.7 47 49.8 42.8 36.8 46.8 52 48.1 54.8 42.7
 41.3 52.2 40.2 46.4 49.3 41.1 41.7 46.1 42.4 48.4 56.2 50 42.6 49.9 45.3
 52.4 45.6 36.3 48.6 44.4 45.8 45.4 44.1 38.2 49.5 49.1 45.2 45.5 42 38.8
 39.5 47.3 38.9 36.2 51.3 35.1 44 44.8 45 51.8 48.3 43.9 50.8 39.3 46 40.7
 34.9 47.4 38.4 36.6 40 39.2 42.2 44.5 47.1 37.4 34.7 35.3 40.4 43.7 41.5
 35.4 41.9 42.5 43.8 38.1 48.7 43.1 43.6 40.3 48.5 33.9 45.1 39.9 42.9
 32.2 37.2 37.5 38 32.4 36 34.3 39.6 33.3 44.3 32 41.2 41.4 33.8 33.4 39.4
 32.8 41.8 39 37.9 31.5 39.8 35.9 37.8 36.1 42.3 38.6 37.3 41 30.8 34.8
 40.8 36.9 35.6 31.6 36.5 34.4 37.6 40.9 38.7 44.2 37.7 31 34.6 33.6 32.5
 31.7 33.7 35 31.8 38.5 36.4 32.9 36.7 29.8 40.1 35.8 37 39.7 31.3 39.1
 30.7 29.3 33.2 28.2 28.5 35.2 34 28.8 29.6 34.1 27.4 34.5 31.2 28.9 27.6
 32.6 35.7 38.3 27.7 32.7 34.2 30.3 29.4 26.7 26.8 26.6 26.5 33.1 26.9
 29.5 29.1 30 33 26.3 30.4 30.1 37.1 29.2 27.9 26 28.4 32.1 31.1 27 30.6
 25.7 31.4 28 31.9 27.3 33.5 30.5 27.8 25.8 27.1 24.3 28.1 26.2 23.9 24.2
 25 28.7 24.5 29 30.2 25.5 25.2 24.4 26.1 24.6 29.7 32.3 30.9 27.5 28.6 23
 25.6 24.7 22.7 29.9 22.4 22.6 28.3 25.1 25.4 26.4 20.8 21.8 23.5 24.9
 23.2 23.6 25.3 22.8 22.3 22 27.2 23.7 21.1 21.9 21.5 21.4 22.2 24 20.4
 20.2 23.1 24.8 23.4 22.1 21.7 21.2 19 20.7 20 18.8 19.1 22.5 19.8 18.9
 20.6 22.9 19.4 19.9 23.8 19.3 21.3 19.5 20.5 18 19.2 23.3 18.2 18.1 17.8
 17.9 18.7 19.6 21 17 25.9 19.7 16.6 18.3 16.8 17.6 15.9 16.9 17.4 15.1
 17.3 14.6 14.4 13.9 15.4 14.1 21.6 14.2 16.3 20.9 16.2 13.5 17.2 13.6
 14.9 15.2 12.9 10.5 12.4 11.9 17.7 13.7 12.1 12.6 14.8 9.4 8.7 8.2 10.7 8
 6.4 '*']




Unique Values in Column Upper 95% Confidence Interval for Death Rate are:  [46.1 144.2 155.1 194.7 165.5 141.4 134.9 138.5 138.3 144.4 130.4 121
 124.1 112.6 119.9 122.3 120.6 116.9 141.6 113.7 110.3 111.2 108.9 113.8
 112 124.9 128.7 124 109.3 110.8 109.9 122.8 111.4 109.7 144.1 108.3 121.3
 122.2 110.2 104.1 96.7 146.9 104.7 98.8 106.7 108.6 103.5 107.4 100.3
 101.7 95.4 101.3 93.5 102.9 109.1 120.4 97.9 118.8 102.6 106.8 96.8 116.2
 102.7 99.4 105.6 99 101.5 120.2 100.8 102.4 103.1 102.5 101.4 106.9 97.1
 104.9 104.6 123.2 106.6 97.7 111 100.9 99.5 98.1 94.8 114.5 107.9 108.7
 115.2 101 94.9 105.4 107 98.4 123 105.9 97.6 96.4 99.1 102.8 88.7 95.3
 96.5 92.3 99.2 107.2 105.3 103.2 109 89.3 100.2 93.7 85.7 96.3 92.6 92.2
 101.1 109.6 98 89.9 91.1 94.3 101.2 88.1 90.6 93.6 94 105.1 135.3 86.1
 88.8 101.8 96.2 93.8 85.3 89.2 92 125 113.1 94.5 101.9 92.4 90.5 98.3
 86.7 95.9 110.4 123.4 104.5 85.8 88.2 90.8 91.8 100.5 89.6 86.4 90 87.1
 96.1 83.7 92.7 89.8 88.6 84.5 106.1 90.7 116.1 85 106.5 85.2 82.8 96.6
 87.7 91.4 87.3 85.6 84.7 90.3 87.6 93.9 87.9 83.8 84.1 94.7 81.4 88.9
 84.8 88.4 84.4 86.9 97.8 82.3 94.2 82.2 84 97 86 80.4 83.1 88 83.5 83.4
 89.4 91.9 97.2 89.5 117.8 76.9 84.2 85.9 83.9 88.3 78.8 80 85.4 93.4 86.8
 81.9 89.1 96 83 92.1 90.2 103.6 85.5 81.5 81.7 105 91.7 87.4 83.3 82.9
 84.6 80.2 79.8 86.2 81 78 77.1 81.8 111.1 82.5 78.6 80.5 77 80.9 87 76.7
 97.4 91 92.5 92.9 80.1 83.6 77.5 78.2 81.3 86.3 87.8 90.4 79.1 79.6 77.6
 96.9 78.1 81.6 77.4 73.8 79 75.5 76.6 74.4 80.7 78.5 82 73 73.7 77.9 75.7
 74.3 75.1 85.1 82.6 76 75.3 78.4 80.3 79.2 87.2 77.8 82.1 71.7 82.4 82.7
 75.2 100.4 73.6 77.3 79.4 79.5 79.9 70.5 98.5 74.7 116 72.5 75.8 79.3
 77.2 84.9 89.7 79.7 72.9 75.4 76.2 78.7 76.3 72.4 73.3 83.2 74.8 72.6
 99.9 71.9 71 75.6 72.2 81.1 74.6 72.1 75.9 69 71.8 73.1 66.8 94.1 71.1
 68.7 78.3 71.6 74 81.2 73.9 76.5 74.5 73.4 66.7 67.9 73.5 74.1 70.9 68.9
 72 74.9 70.4 78.9 84.3 70.3 68.6 86.6 69.2 100.7 69.4 70.6 68.4 71.5 67.8
 100.1 67.2 76.8 70.8 64.6 67.3 69.8 68.5 94.6 75 66.5 66.4 68.8 70.7 80.6
 91.6 67.7 76.4 70.2 67.1 66.1 63.8 62.9 65.7 69.9 67.4 67 65.6 65 65.3
 71.3 70 65.9 69.7 73.2 66.9 65.2 64.4 67.5 64.5 72.7 67.6 65.8 92.8 64.7
 69.1 68.1 91.5 93.3 69.6 66.6 62.5 77.7 66 72.3 64.8 63.6 62.4 64 62.1
 62.2 71.4 63.4 63.7 64.2 60.1 63 68 61.5 59.3 95.7 59.8 62.8 62 60.6 61.9
 68.3 63.9 60 62.3 72.8 63.3 69.5 63.1 61.7 60.9 64.9 63.2 59.5 66.3 60.5
 62.6 59 71.2 61.6 65.4 61.8 58.5 68.2 59.7 60.4 58 59.4 57.7 58.4 66.2
 64.3 65.5 57.8 63.5 61 61.4 58.6 58.7 61.1 69.3 58.8 58.1 62.7 60.8 61.2
 65.1 59.6 56.4 60.3 59.1 56.1 56.7 60.2 55.6 57.1 58.2 55.5 56.9 56.8
 60.7 55.9 56.3 59.9 57.4 55.3 61.3 54.5 55.2 57.2 56.6 54.9 57.9 56 70.1
 54.2 57.3 59.2 64.1 56.5 54 53.9 55.7 55 52.9 55.4 54.7 57.5 52.7 57.6
 53.2 55.8 52.3 56.2 53.8 76.1 58.3 53 53.1 57 55.1 52.2 53.5 54.4 52.1
 52.8 54.3 53.3 52 52.4 51.6 54.8 51.3 50.1 54.1 52.6 51.1 58.9 49.6 51.9
 51.4 49.8 51.8 54.6 74.2 51.5 50 51.2 51 50.5 49.9 51.7 50.8 48.5 49.7
 49.2 49.1 48.7 47.6 49.3 48.8 53.6 50.4 48 48.4 50.6 52.5 48.2 50.3 47.4
 46.8 53.4 47.3 48.1 49.5 45.5 50.7 46 48.6 45.3 46.6 50.9 45.7 46.7 44.8
 45 44.2 47.8 47.9 44.1 43.9 46.9 47.1 46.3 44 45.9 44.3 44.5 45.4 48.3
 43.7 49 45.8 42.6 43.8 44.7 48.9 45.2 43.1 44.6 42.2 42.9 47.2 46.2 41.4
 42.4 47.7 43.4 41.6 42.5 41.8 53.7 42.7 45.1 40.4 46.4 41 41.5 42.3 39.9
 40.6 44.9 47.5 47 40.8 41.1 41.7 43.2 46.5 40.2 41.9 38.9 38.5 38.1 38.2
 49.4 39.1 38.8 37.7 38.6 36.9 50.2 38 37.4 39 39.7 39.8 37.1 36.1 36.2
 40.9 36 35.9 43.3 40.3 38.4 36.8 38.3 39.4 39.2 35.5 37.5 43.6 34.8 38.7
 34.4 42 35.7 33.5 34.6 37.6 36.6 33.4 35.4 40 34.3 35.8 33.2 31.6 42.8
 44.4 32.6 32.2 31.4 32.1 30.8 32.7 32.5 45.6 37.8 31.7 32 42.1 33.7 28.7
 35.6 30.9 37 31 30.2 34.1 37.2 30.6 27.2 30.4 32.4 28.8 26.4 39.6 26 27.5
 26.3 35.3 29.9 30.3 26.5 36.7 24.2 25.9 31.9 23.6 35 34.9 24.1 27.3 27.9
 22.9 23.9 19.9 25.4 23.2 14.4 16.2 12.8 '*']




Unique Values in Column Average Deaths per Year are:  [157376 43 18 5 8 19 22 16 14 9 17 33 25 47 21 6 29 39 34 45 24 28 27 23 3
 78 4 49 26 67 77 12 36 7 42 11 20 13 10 32 71 46 92 15 37 31 59 38 65 41
 63 50 57 60 40 70 30 157 58 44 61 75 52 73 55 48 111 35 68 53 90 132 99
 81 54 139 204 88 69 102 64 170 545 79 200 289 150 95 51 85 119 388 72 104
 122 127 80 112 298 512 116 103 129 113 86 62 107 97 138 216 211 117 186
 98 221 219 118 109 94 903 121 198 1136 422 91 115 233 66 331 105 101 83
 165 100 347 154 84 168 87 159 376 93 74 409 268 183 500 76 172 487 275
 169 398 179 223 162 89 439 126 130 124 465 108 553 185 457 171 164 279
 206 114 56 350 620 328 135 262 352 145 527 484 143 258 156 396 381 110
 862 181 838 245 356 777 281 251 423 277 176 131 134 326 292 271 163 167
 213 241 616 901 471 442 327 144 96 106 201 199 191 405 194 210 240 574
 177 175 300 467 2369 654 232 151 340 751 193 142 390 189 227 123 354 317
 802 595 713 424 366 314 236 182 187 270 247 567 178 148 408 1243 257 299
 441 202 625 133 274 174 827 362 249 152 136 464 852 1463 808 319 207 681
 291 196 404 1097 411 605 120 402 365 438 528 324 397 146 495 824 377 979
 230 573 2876 254 740 250 885 472 242 263 137 '*']




Unique Values in Column Recent Trend (2) are:  ['falling' 'stable' '**' 'rising' '*']




Unique Values in Column Recent 5-Year Trend (2) in Death Rates are:  [-2.4 -0.6 1.7 '**' 2.2 -2.2 22.9 0.8 1.3 1.4 -0.2 0.5 0.6 -0.3 0.3 1.2
 -0.4 -1.1 -0.1 0.1 0.2 0.9 -0.5 1.5 0.4 6.8 -8.6 1 1.8 -0.8 0 3.4 1.6 1.1
 -0.7 -0.9 3 0.7 2.3 -1 -1.5 2.1 -1.2 -1.8 -15.1 -1.3 -2.3 -1.9 -4 5.5
 -4.8 -1.4 2.4 1.9 -2 -3 -2.1 -1.6 -6.1 -2.6 -1.7 2.7 -14.2 -2.7 -3.4 -2.5
 -11.7 5.2 -18.9 13.2 6.1 -2.8 -5.8 -4.1 2.6 -3.2 -5.4 -9.6 -6.3 -5.2 3.5
 -33.4 -12.4 -12.9 -8.2 -2.9 -7.2 -5.7 -11.9 -3.8 -9.5 -3.9 -4.4 8.7 -5.6
 -4.6 -4.3 -19.6 2.8 -3.3 -12.2 -13.4 2 -8.8 -4.5 -7.6 -5.3 -7.1 4.2 -8.3
 9.6 -6.2 -3.5 -5.5 -3.1 -10.6 -5.9 -10.4 -13.6 5.3 2.5 6.9 -3.7 31.1
 -16.9 -31.5 -5 -5.1 -6.5 -6.9 -13.8 -3.6 -17.2 -18.4 -6 -8.4 -8.5 -10.5
 21.4 -28.9 -7.5 -4.7 -10 -4.2 -6.8 -14 -10.2 -4.9 '*']




Unique Values in Column Lower 95% Confidence Interval for Trend are:  [-2.6 -2.7 0 '**' -0.4 -4.3 6.9 -0.7 -0.8 -1.4 -1.2 -1.9 -1.7 -1.6 -0.6
 -2.2 -1.3 -1 -0.9 -2.1 -1.1 -1.8 0.1 -11.9 0.6 0.9 -2 -2.4 -0.5 -3 -0.3
 0.5 0.7 0.2 -0.1 -0.2 -2.3 -3.2 -2.5 -2.8 -2.9 -1.5 -3.4 -3.7 -3.3 -3.6
 -24.4 -4.1 -5.9 -3.1 0.4 -3.5 -6 -8.6 -3.8 -4 -4.4 -5.4 0.3 -4.2 -7.6
 -11.3 -5.1 -3.9 -27.8 -6.9 -5 -22.8 -35 -4.5 -10.2 -7.2 -4.7 -5.2 -15.1
 -19.2 -14.5 -4.6 -8.5 -60.9 -8.9 -29.4 -23.8 -18.4 -4.8 -7.7 -4.9 -11.6
 -5.7 -21.7 -5.8 -20 -7 -23.7 -6.1 -8 -7.9 -8.8 -41.3 -5.3 -24.5 -15.7
 -10.5 -9 -12.3 0.8 -14 -9.2 -28.4 -6.3 -21.6 1 -10.3 -6.6 -7.1 -11 -10.1
 -18.9 -23.1 -6.8 -5.5 -16.7 -30.9 -7.3 -15.3 -60.2 -7.8 -5.6 -9.3 -10.7
 -11.4 -12.2 -27.2 -6.2 -13.3 -19.6 -9.7 -32.1 -27.5 -14.9 -6.7 -13.7
 -18.2 -10.8 -45.9 -12 -21.8 -16.2 -6.4 -9.5 -19.7 -16.5 -22.4 -17.4 '*']




Unique Values in Column Upper 95% Confidence Interval for Trend are:  [-2.2 1.6 3.4 '**' 4.8 0 41.4 2.4 4.3 3 1 2.1 2 1.3 1.9 2.8 1.2 3.7 3.1
 1.8 2.5 2.6 2.2 13.9 1.7 -5.1 1.5 3.8 1.4 0.5 2.3 2.7 2.9 0.6 6.2 3.2 3.3
 3.6 1.1 4.2 0.9 3.5 0.7 4.1 5.1 0.8 0.2 0.3 0.4 4.5 4.7 0.1 -4.6 -0.6
 -0.1 -0.8 -0.3 -1.9 12.2 -0.5 5.5 -0.4 -0.2 4 -1 -1.1 5.7 -0.7 3.9 -0.9
 -2 -1.6 -1.3 10.4 30.5 12.9 -1.7 -1.4 4.9 5.4 4.4 9.8 -1.2 6.8 13.3 -1.8
 8.6 4.6 -1.5 -2.6 25.4 7.3 33.5 -3.2 10.2 -2.1 6.4 -3.8 5 -2.7 -2.9 -2.5
 -3 51.8 7.2 18.9 -2.3 -4 -3.5 12.5 5.2 17.8 78.1 17.9 20.6 5.3 -3.7 -3.6
 -2.8 -8.1 -2.4 -3.4 -3.1 65.2 -6.5 -3.3 -10.3 -4.8 '*']

Met Objective of 45.5? (1)                      None
Age-Adjusted Death Rate                         None
Lower 95% Confidence Interval for Death Rate    None
Upper 95% Confidence Interval for Death Rate    None
Average Deaths per Year                         None
Recent Trend (2)                                None
Recent 5-Year Trend (2) in Death Rates          None
Lower 95% Confidence Interval for Trend         None
Upper 95% Confidence Interval for Trend         None
dtype: object

In [104]:
weird_characters = ['*', '_', '__', '**']

def fix_strings(row):
    for col in cat_cols:
        if row[col] in weird_characters:
            row[col] = np.nan
    
    return row

death[cat_cols] = death[cat_cols].apply(fix_strings, axis = 1)

In [105]:
death.to_csv('death_cleaned.csv', index = False)

### Death Cleaned